--CREATE DATABASE QLYLAIXE
---BẢNG USER
IF OBJECT_ID('USERS') IS NOT NULL
DROP TABLE USERS
GO
CREATE TABLE USERS
(
     EMAIL		VARCHAR(50) NOT NULL,
	 PASS		VARCHAR(20) NOT NULL ,
	 ROLES NVARCHAR(20) NOT NULL,
	 CONSTRAINT PK_USERS PRIMARY KEY(EMAIL)
)

--BẢNG LOAIDE
IF OBJECT_ID('LOAIDE') IS NOT NULL
	DROP TABLE LOAIDE
GO
CREATE TABLE LOAIDE
(
	ID_LOAIDE	INT NOT NULL IDENTITY(1,1) ,
	TENLOAI		NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_LOAIDE PRIMARY KEY(ID_LOAIDE)
)
--RESERT IDENTITY
TRUNCATE TABLE DBO.LOAIDE

--BẢNG DETHI
IF OBJECT_ID('DETHI') IS NOT NULL
	DROP TABLE DETHI
GO
CREATE TABLE DETHI
(
	ID_DETHI	INT NOT NULL IDENTITY(1,1),
	TRANGTHAI	nvarchar(10) not null,
	EMAIL		VARCHAR(50) NOT NULL ,
	Timer		int	not null,
	ID_LOAIDE	INT NOT NULL,
	CONSTRAINT PK_DETHI PRIMARY KEY(ID_DETHI),
	CONSTRAINT FK_USERS_DETHI FOREIGN KEY (EMAIL) REFERENCES USERS ,
	CONSTRAINT FK_LOAIDE_DETHI FOREIGN KEY(ID_LOAIDE) REFERENCES LOAIDE
)
--RESERT IDENTITY 
TRUNCATE TABLE DBO.DETHI

--BẢNG LOAICAUHOI
IF OBJECT_ID('LOAICAUHOI') IS NOT NULL
	DROP TABLE LOAICAUHOI
GO
CREATE TABLE LOAICAUHOI
(
	ID_LOAICAUHOI	INT NOT NULL IDENTITY(1,1),
	TENLOAI			NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_LOAICAUHOI PRIMARY KEY(ID_LOAICAUHOI)
)
--RESERT IDENTITY
TRUNCATE TABLE DBO.LOAICAUHOI

--BẢNG CAUHOI
IF OBJECT_ID('CAUHOI') IS NOT NULL
	DROP TABLE CAUHOI
GO
CREATE TABLE CAUHOI
(
	ID_CAUHOI		INT NOT NULL IDENTITY(1,1),
	NOIDUNG			NVARCHAR(500) NOT NULL ,
	HINH			VARCHAR(30) NULL ,
	ID_LOAICAUHOI	INT NOT NULL ,
	CONSTRAINT PK_CAUHOI PRIMARY KEY(ID_CAUHOI),
	CONSTRAINT FK_LOAICAUHOI_CAUHOI FOREIGN KEY(ID_LOAICAUHOI) REFERENCES DBO.LOAICAUHOI 
)
---RESERT IDENTITY
TRUNCATE TABLE DBO.CAUHOI

---BẢNG CAUHOI_DETHI	
IF OBJECT_ID('CAUHOI_DETHI') IS NOT NULL
	DROP TABLE CAUHOI_DETHI
GO
CREATE TABLE CAUHOI_DETHI
(
	ID_CAUHOI		INT NOT NULL,
	ID_DETHI		INT NOT NULL,
	ID_CAUTRALOI	INT NULL,
	TRANGTHAI		BIT NULL  ,
	CONSTRAINT PK_CAUHOI_DETHI PRIMARY KEY(ID_CAUHOI,ID_DETHI),
	CONSTRAINT FK_CAUHOI_CAUHOI_DETHI FOREIGN KEY(ID_CAUHOI) REFERENCES DBO.CAUHOI  ,
	CONSTRAINT FK_DETHI_CAUHOI_DETHI FOREIGN KEY(ID_DETHI) REFERENCES DBO.DETHI
)

---BẢNG DAPAN
IF OBJECT_ID('DAPAN') IS NOT NULL
	DROP TABLE DAPAN 
GO
CREATE TABLE DAPAN
(
	ID_DAPAN	INT NOT NULL IDENTITY(1,1) ,
	NOIDUNG		NVARCHAR(500) NOT NULL ,
	TRANGTHAI	BIT NOT NULL ,
	GIAITHICH	NVARCHAR(500)  NULL ,
	ID_CAUHOI	INT NOT NULL ,
	CONSTRAINT PK_DAPAN PRIMARY KEY(ID_DAPAN),
	CONSTRAINT FK_DAPAN FOREIGN KEY(ID_CAUHOI) REFERENCES DBO.CAUHOI 
)
--RESERT IDENTITY
TRUNCATE TABLE DBO.DAPAN 

-- CHÈN DỮ LIỆU VÀO BẢNG USSER
DELETE FROM USERS 
INSERT INTO DBO.USERS (EMAIL,PASS,ROLES) VALUES
('HAILVPH13040@FPT.EDU.VN','ABC123','ADMIN'),
('QUANGVMPH12936@FPT.EDU.VN', '123','USER'),
('CUONGDVPH13100@FPT.EDU.VN','123','USER'),
('admin','1','admin')

--CHÈN DỮ LIỆU BẢNG LOAIDE

DELETE FROM LOAIDE
INSERT INTO DBO.LOAIDE (TENLOAI) VALUES 
(N'ĐỀ THI'),
(N'Ôn tập SA HÌNH'),
(N'Ôn tập câu liệt LIỆT'),
(N'Ôn tập KHÁI NIỆM, QUY TẮC')



-- CHÈN DỮ LIỆU VÀO BẢNG LOAICAUHOI
DELETE FROM LOAICAUHOI
INSERT INTO DBO.LOAICAUHOI (TENLOAI) VALUES
(N'CÂU HỎI KHÁI NIỆM , QUY TẮC'),
(N'CÂU HỎI SA HÌNH'),
(N'CÂU HỎI LIỆT')

--CHÈN DỮ LIỆU BẢNG CAUHOI
DELETE FROM CAUHOI
INSERT INTO  DBO.CAUHOI (NOIDUNG,HINH,ID_LOAICAUHOI) VALUES
(N'Phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại là gì?','',1),
(N'“Làn đường” là gì?','',1),
(N'Trong các khái niệm dưới đây, “dải phân cách” được hiểu như thế nào là đúng?','',1),
(N'“Dải phân cách” trên đường bộ gồm những loại nào?','',1),
(N'Người lái xe được hiểu như thế nào trong các khái niệm dưới đây?','',1),
(N'Đường mà trên đó phương tiện tham gia giao thông được các phương tiện giao thông đến từ các hướng khác nhường đường khi qua nơi đường giao nhau,được cắm biển báo hiệu đường ưu tiên là loại đường gì?','',1),
(N'Khái niệm “phương tiện giao thông cơ giới đường bộ” được hiểu như thế nào là đúng?','',1),
(N'Khái niệm “phương tiện giao thông thô sơ đường bộ” được hiểu như thế nào là đúng?','',1),
(N'“Phương tiện tham gia giao thông đường bộ” gồm những loại nào?','',1),
(N'“Người tham gia giao thông đường bộ” gồm những đối tượng nào?','',1),
(N'“Người điều khiển phương tiện tham gia giao thông đường bộ” gồm những đối tượng nào dưới đây?','',1),
(N'Khái niệm “người điều khiển giao thông” được hiểu như thế nào là đúng?','',1),
(N'“Trong các khái niệm dưới đây khái niệm “dừng xe” được hiểu như thế nào là đúng?','',1),
(N'Khái niệm “đỗ xe” được hiểu như thế nào là đúng?','',1),
(N'(Câu hỏi liệt) Cuộc đua xe chỉ được thực hiện khi nào?','',3),
(N'(Câu hỏi liệt) Người điều khiển phương tiện giao thông đường bộ mà trong cơ thể có chất ma túy có bị nghiêm cấm hay không?','',3),
(N'(Câu hỏi liệt) Sử dụng rượu, bia khi lái xe, nếu bị phát hiện thì bị xử lý như thế nào?','',3),
(N'(Câu hỏi liệt) Theo luật phòng chống tác hại của rượu, bia, đối tượng nào dưới đây bị cấm sử dụng rượu, bia khi tham gia giao thông?','',3),
(N'(Câu hỏi liệt) Hành vi điều khiển xe cơ giới chạy quá tốc độ quy định, giành đường, vượt ẩu có bị nghiêm cấm hay không?','',3),
(N'Khi lái xe trong khu đô thị và đông dân cư trừ các khu vực có biển cấm sử dụng còi, người lái xe được sử dụng còi như thế nào trong các trường hợp dưới đây?','',1),
(N'“Người lái xe sử dụng đèn như thế nào khi lái xe trong khu đô thị và đông dân cư vào ban đêm?','',1),
(N'Trong trường hợp đặc biệt, để được lắp đặt, sử dụng còi, đèn không đúng với thiết kế của nhà sản xuất đối với từng loại xe cơ giới bạn phải đảm bảo yêu cầu nào dưới đây?','',1),
(N'Ở phần đường dành cho người đi bộ qua đường, trên cầu, đầu cầu, đường cao tốc, đường hẹp, đường dốc,tại nơi đường bộ giao nhau cùng mức với đường sắt có được quay đầu xe hay không?','',3),
(N'Bạn đang lái xe phía trước có một xe cảnh sát giao thông không phát tín hiệu ưu tiên bạn có được phép vượt hay không?','',1),
(N'Bạn đang lái xe phía trước có một xe cứu thương đang phát tín hiệu ưu tiên bạn có được phép vượt hay không?','',1),
(N'(Câu hỏi liệt) Người điều khiển xe mô tô hai bánh, ba bánh, xe gắn máy có được phép sử dụng xe để kéo hoặcđẩy các phương tiện khác khi tham gia giao thông không?','',3),
(N'(Câu hỏi liệt) Khi điều khiển xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy, những hành vi buông cả hai tay; sử dụng xe để kéo, đẩy xe khác, vật khác;sử dụng chân chống của xe quệt xuống đường khi xe đang chạy có được phép hay không?','',3),
(N'(Câu hỏi liệt) Khi điều khiển xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy, những hành vi nào không được phép?','',3),
(N'(Câu hỏi liệt) Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được mang, vác vật cồng kềnh hay không?','',3),
(N'(Câu hỏi liệt) Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được bám, kéo hoặc đẩy các phương tiện khác không?','',3),
(N'(Câu hỏi liệt) Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được sử dụng ô khi trời mưa hay không?','',3),
(N'(Câu hỏi liệt) Khi đang lên dốc người ngồi trên xe mô tô có được kéo theo người đang điều khiển xe đạp hay không?','',3),
(N'(Câu hỏi liệt) Hành vi sử dụng xe mô tô để kéo, đẩy xe mô tô khác bị hết xăng đến trạm mua xăng có được phép hay không?','',3),
(N'(Câu hỏi liệt) Hành vi vận chuyển đồ vật cồng kềnh bằng xe mô tô, xe gắn máy khi tham gia giao thông có được phép hay không?','',3),
(N'Người đủ bao nhiêu tuổi trở lên thì được điều khiển xe mô tô hai bánh, xe mô tô ba bánh có dung tích xi lanh từ 50 cm3 trở lên và các loại xe có kết cấu tương tự; xe ô tô tải,máy kéo có trọng tải dưới 3,5 tấn; xe ô tô chở người đến 9 chỗ ngồi?','',1),
(N'Người đủ 16 tuổi được điều khiển các loại xe nào dưới đây?','',1),
(N'Người có giấy phép lái xe mô tô hạng A1 không được phép điều khiển loại xe nào dưới đây?','',1),
(N'Người có giấy phép lái xe mô tô hạng A1 được phép điều khiển loại xe nào dưới đây?','',1),
(N'Biển báo hiệu có dạng hình tròn, viền đỏ, nền trắng, trên nền có hình vẽ hoặc chữ số, chữ viết màu đen là loại biển gì dưới đây?','CAU39',2),
(N'Biển báo hiệu có dạng tam giác đều, viền đỏ, nền màu vàng, trên có hình vẽ màu đen là loại biển gì dưới đây?','CAU40',2),
(N'Biển báo hiệu hình tròn có nền xanh lam có hình vẽ màu trắng là loại biển gì dưới đây?','CAU41',2),
(N'Biển báo hiệu hình chữ nhật hoặc hình vuông hoặc hình mũi tên nền xanh lam là loại biển gì dưới đây?','CAU42',2),
(N'Khi sử dụng giấy phép lái xe đã khai báo mất để điều khiển phương tiện cơ giới đường bộ, ngoài việc bị thu hồi giấy phép lái xe, chịu trách nhiệm trước pháp luật,người lái xe không được cấp giấy phép lái xe trong thời gian bao nhiêu năm?','',1),
(N'Khi gặp hiệu lệnh như dưới đây của cảnh sát giao thông thì người tham gia giao thông phải đi như thế nào là đúng quy tắc giao thông?','CAU44',2),
(N' Khi gặp hiệu lệnh như dưới đây của cảnh sát giao thông thì người tham gia giao thông phải đi như thế nào là đúng quy tắc giao thông?','CAU45',2),
(N'Tại nơi có biển báo hiệu cố định lại có báo hiệu tạm thời thì người tham gia giao thông phải chấp hành hiệu lệnh của báo hiệu nào?','',1),
(N'Trên đường có nhiều làn đường cho xe đi cùng chiều được phân biệt bằng vạch kẻ phân làn đường, người điều khiển phương tiện phải cho xe đi như thế nào?','',1),
(N'Trên đường một chiều có vạch kẻ phân làn đường, xe thô sơ và xe cơ giới phải đi như thế nào là đúng quy tắc giao thông? ','',1),
(N'Bạn đang lái xe trong khu vực đô thi từ 22 giờ đến 5 giờ sáng hôm sau và cần vượt một xe khác, bạn cần báo hiệu như thế nào để đảm bảo an toàn giao thông? ','',1),
(N'Khi điều khiển xe chạy trên đường biết có xe sau xin vượt nếu đủ điều kiện an toàn người lái xe phải làm gì?','',1),
(N'Khi muốn chuyển hướng, người lái xe phải thực hiện như thế nào để đảm bảo an toàn giao thông?','',1),
(N'Khi tránh xe đi ngược chiều, các xe phải nhường đường như thế nào là đúng quy tắc giao thông?','',1),
(N'Bạn đang lái xe trên đường hẹp, xuống dốc và gặp một xe đang đi lên dốc, bạn cần làm gì?','',1),
(N'Tại nơi đường giao nhau, người lái xe đang đi trên đường không ưu tiên phải nhường đường như thế nào là đúng quy tắc giao thông?','',1),
(N'Tại nơi đường giao nhau không có báo hiệu đi theo vòng xuyến, người điều khiển phương tiện phải nhường đường như thế nào là đúng quy tắc giao thông?','',1),
(N'Tại nơi đường bộ giao nhau cùng mức với đường sắt chỉ có đèn tín hiệu hoặc chuông báo hiệu, khi đèn tín hiệu màu đỏ đã bật sáng hoặc có tiếng chuông báo hiệu, người tham gia giao thông phải dừng lại ngay và giữ khoảng cách tối thiểu bao nhiêu mét tính từ ray gần nhất?','',1),
(N'Người điều khiển phương tiện tham gia giao thông trong hầm đường bộ ngoài việc phải tuân thủ các quy tắc giao thông còn phải thực hiện những quy định nào dưới đây?','',1),
(N'Người ngồi trên xe mô tô 2 bánh, xe gắn máy phải đội mũ bảo hiểm có cài quai đúng quy cách khi nào?','',1),
(N'Người điều khiển xe mô tô hai bánh, xe gắn máy được phép chở tối đa 2 người trong những trường hợp nào?','',1),
(N'Người điều khiển xe mô tô hai bánh, xe gắn máy không được thực hiện những hành vi nào dưới đây?','',1),
(N'(Câu hỏi liệt) Người điều khiển xe mô tô hai bánh, xe gắn máy có được đi xe dàn hàng ngang; xe đi vào phần đường dành cho người đi bộ và phương tiện khác; sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính) hay không?','',3),
(N'Người lái xe phải giảm tốc độ thấp hơn tốc độ tối đa cho phép (có thể dừng lại một cách an toàn) trong trường hợp nào dưới đây?','',1),
(N'Tại ngã ba hoặc ngã tư không có đảo an toàn, người lái xe phải nhường đường như thế nào là đúng trong các trường hợp dưới đây?','',1),
(N'Khi điều khiển xe cơ giới, người lái xe phải bật đèn tín hiệu báo rẽ trong trường hợp nào sau đây?','',1),
(N'Trên đoạn đường hai chiều không có giải phân cách giữa, người lái xe không được vượt xe khác trong các trường hợp nào dưới đây?','',1),
(N'Người lái xe mô tô xử lý như thế nào khi cho xe mô tô phía sau vượt?','',1),
(N'Trong các trường hợp dưới đây, để bảo đảm an toàn khi tham gia giao thông, người lái xe mô tô cần thực hiện như thế nào?','',1),
(N'Đường bộ trong khu vực đông dân cư gồm những đoạn đường nào dưới đây?','',1),
(N'Tốc độ tối đa cho phép đối với xe máy chuyên dùng, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự trên đường bộ (trừ đường cao tốc) không được vượt quá bao nhiêu km/h?','',1),
(N'Trên đường bộ (trừ đường cao tốc) trong khu vực đông dân cư, đường đôi có dải phân cách giữa, xe mô tô hai bánh, ô tô chở người đến 30 chỗ tham gia giao thông với tốc độ tối đa cho phép là bao nhiêu?','',1),
(N'Trên đường bộ (trừ đường cao tốc) trong khu vực đông dân cư, đường hai chiều không có dải phân cách giữa, xe mô tô hai bánh, ô tô chở người đến 30 chỗ tham gia giao thông với tốc độ tối đa cho phép là bao nhiêu?','',1),
(N'Trên đường bộ (trừ đường cao tốc) trong khu vực đông dân cư, đường hai chiều hoặc đường một chiều có một làn xe cơ giới, loại xe nào dưới đây được tham gia giao thông với tốcđộ tối đa cho phép là 50 km/h?','',1),
(N' Khi điều khiển xe chạy với tốc độ dưới 60 km/h, để đảm bảo khoảng cách an toàn giữa hai xe, người lái xe phải điều khiển xe như thế nào?','',1),
(N'Người lái xe phải giảm tốc độ thấp hơn tốc độ tối đa cho phép đến mức cần thiết, chú ý quan sát và chuẩn bị sẵn sàng những tình huống có thể xảy ra để phòng ngừatai nạn trong các trường hợp nào dưới đây?','',1),
(N'Các phương tiện tham gia giao thông đường bộ (kể cả những xe có quyền ưu tiên) đều phải dừng lại bên phải đường của mình và trước vạch “dừng xe” tại các điểm giao cắt giữa đường bộ và đường sắtkhi có báo hiệu dừng nào dưới đây?','',1),
(N'Tác dụng của mũ bảo hiểm đối với người ngồi trên xe mô tô hai bánh trong trường hợp xảy ra tai nạn giao thông là gì?','',1),
(N'Tại nơi đường giao nhau, người lái xe đang đi trên đường không ưu tiên phải xử lý như thế nào là đúng quy tắc giao thông?','',1),
(N'(Câu hỏi liệt) Người lái xe phải xử lý như thế nào khi quan sát phía trước thấy người đi bộ đang sang đường tại nơi có vạch đường dành cho người đi bộ để đảm bảo an toàn?','',3),
(N'Theo Luật Giao thông đường bộ, tín hiệu đèn giao thông gồm 3 màu nào dưới đây?','',1),
(N'Tại nơi đường giao nhau, khi đèn điều khiển giao thông có tín hiệu màu vàng, người điều khiển giao thông phải chấp hành như thế nào là đúng quy tắc giao thông?','',1),
(N'Để báo hiệu cho xe phía trước biết xe mô tô của bạn muốn vượt, bạn phải có tín hiệu như thế nào dưới đây?','',1),
(N' Người điều khiển xe mô tô phải giảm tốc độ và hết sức thận trọng khi qua những đoạn đường nào dưới đây?','',1),
(N'Khi gặp xe buýt đang dừng đón, trả khách, người điều khiển xe mô tô phải xử lý như thế nào dưới đây để đảm bảo an toàn giao thông?','',1),
(N'Khái niệm về văn hóa giao thông được hiểu như thế nào là đúng?','',1),
(N'Trong các hành vi dưới đây, người lái xe mô tô có văn hóa giao thông phải ứng xử như thế nào?','',1),
(N'Trong các hành vi dưới đây, người lái xe ô tô, mô tô có văn hóa giao thông phải ứng xử như thế nào?','',1),
(N' Khi xảy ra tai nạn giao thông, có người bị thương nghiêm trọng, người lái xe và người có mặt tại hiện trường vụ tai nạn phải thực hiện các công việc gì dưới đây?','',1),
(N'Trên đường đang xảy ra ùn tắc có những hành vi nào sau đây là thiếu văn hóa khi tham gia giao thông?','',1),
(N'(Câu hỏi liệt) Khi điều khiển xe mô tô tay ga chạy xuống đường dốc dài, độ dốc cao, người lái xe cần thực hiện những thao tác nào dưới đây để đảm bảo an toàn?','',3),
(N'Khi quay đầu xe, người lái xe cần phải quan sát và thực hiện các thao tác nào để đảm bảo an toàn giao thông?','',1),
(N'Khi tránh nhau trên đường hẹp, người lái xe cần phải chú ý những điểm nào để đảm bảo an toàn giao thông?','',1),
(N'Khi điều khiển xe trên đường vòng người lái xe cần phải làm gì để đảm bảo an toàn?','',1),
(N'Để đạt được hiệu quả phanh cao nhất, người lái xe mô tô phải sử dụng các kỹ năng như thế nào dưới đây?','',1),
(N'(Câu hỏi liệt) Khi đang lái xe mô tô và ô tô, nếu có nhu cầu sử dụng điện thoại để nhắn tin hoặc gọi điện, người lái xe phải thực hiện như thế nào trong các tình huống nêu dưới đây?','',3),
(N'Những thói quen nào dưới đây khi điều khiển xe mô tô tay ga tham gia giao thông dễ gây tai nạn nguy hiểm?','',1),
(N'Khi điều khiển xe mô tô quay đầu người lái xe cần thực hiện như thế nào để đảm bảo an toàn?','',1),
(N'Tay ga trên xe mô tô hai bánh có tác dụng gì trong các trường hợp dưới đây?','',1),
(N'Gương chiếu hậu của xe mô tô hai bánh có tác dụng gì trong các trường hợp dưới đây?','',1),
(N' Để đảm bảo an toàn khi tham gia giao thông, người lái xe mô tô hai bánh cần điều khiển tay ga như thế nào trong các trường hợp dưới đây?','',1),
(N'Kỹ thuật cơ bản để giữ thăng bằng khi điều khiển xe mô tô đi trên đường gồ ghề như thế nào trong các trường hợp dưới đây?','',1),
(N'Biển nào dưới đây xe gắn máy được phép đi vào?','CAU101',2),
(N'Biển nào báo hiệu cấm xe mô tô hai bánh đi vào?','CAU102',2),
(N'Khi gặp biển nào thì xe mô tô hai bánh được đi vào?','CAU103',2),
(N'Biển nào cấm quay đầu xe?','CAU104',2),
(N'Biển nào cấm xe rẽ trái?','CAU105',2),
(N'Khi gặp biển nào xe được rẽ trái?','CAU106',2),
(N'Biển nào cấm các phương tiện giao thông đường bộ rẽ phải?','CAU107',2),
(N'Biển nào cấm các phương tiện giao thông đường bộ rẽ trái?','CAU108',2),
(N'Biển nào cho phép xe rẽ trái?','CAU109',2),
(N'Biển nào xe được phép quay đầu nhưng không được rẽ trái?','CAU110',2),
(N'Biển nào xe được phép quay đầu nhưng không được rẽ trái ?','CAU111',2),
(N'Biển nào là biển “Cấm đi ngược chiều”?','CAU112',2),
(N'Biển nào dưới đây các phương tiện không được phép đi vào?','CAU113',2),
(N'Khi gặp biển nào xe ưu tiên theo luật định vẫn phải dừng lại?','CAU114',2),
(N'Biển nào cấm tất cả các loại xe cơ giới và thô sơ đi lại trên đường, trừ xe ưu tiên theo luật định (nếu đường vẫn cho xe chạy được)?','CAU115',2),
(N'Gặp biển nào xe xích lô được phép đi vào?','CAU116',2),
(N'Gặp biển nào xe lam, xe xích lô máy được phép đi vào?','CAU117',2),
(N'Biển báo này có ý nghĩa như thế nào?','CAU118',2),
(N'Chiều dài đoạn đường 500 m từ nơi đặt biển này, người lái xe có được phép bấm còi không?','CAU119',2),
(N'Biển nào xe mô tô hai bánh được đi vào?','CAU120',2),
(N'Biển nào xe mô tô hai bánh không được đi vào?','CAU121',2),
(N'Biển báo nào báo hiệu bắt đầu đoạn đường vào phạm vi khu dân cư, các phương tiện tham gia giao thông phải tuân theo các quy định đi đường được áp dụng ở khu đông dân cư?','CAU122',2),
(N'Gặp biển nào người lái xe phải nhường đường cho người đi bộ ?','CAU123',2),
(N'Biển nào chỉ đường dành cho người đi bộ, các loại xe không được đi vào khi gặp biển này?','CAU124',2),
(N'Biển nào báo hiệu “Đường dành cho xe thô sơ”?','CAU125',2),
(N'Biển nào báo hiệu sắp đến chỗ giao nhau nguy hiểm?','CAU126',2),
(N'Biển nào báo hiệu “Giao nhau với đường sắt có rào chắn”?','CAU127',2),
(N'Biển nào báo hiệu “Giao nhau với tín hiệu đèn”?','CAU128',2),
(N'Biển nào báo hiệu nguy hiểm giao nhau với đường sắt?','CAU129',2),
(N'Biển nào báo hiệu đường sắt giao nhau với đường bộ không có rào chắn?','CAU130',2),
(N'Biển nào báo hiệu sắp đến chỗ giao nhau giữa đường bộ và đường sắt?','CAU131',2),
(N'Biển nào báo hiệu, chỉ dẫn xe đi trên đường này được quyền ưu tiên qua nơi giao nhau?','CAU132',2),
(N'Biển nào báo hiệu “Giao nhau với đường không ưu tiên”?','CAU133',2),
(N'Biển nào báo hiệu “Giao nhau với đường ưu tiên”?','CAU134',2),
(N'Biển nào báo hiệu “Đường bị thu hẹp”?','CAU135',2),
(N'Khi gặp biển nào, người lái xe phải giảm tốc độ, chú ý xe đi ngược chiều, xe đi ở phía đường bị hẹp phải nhường đường cho xe đi ngược chiều?','CAU136',2),
(N'Biển nào báo hiệu “Đường giao nhau” của các tuyến đường cùng cấp?','CAU137',2),
(N'Biển nào báo hiệu “Đường đôi”?','CAU138',2),
(N'Biển nào báo hiệu “Đường đôi”?','CAU139',2),
(N'Biển nào báo hiệu “Giao nhau với đường hai chiều”?','CAU140',2),
(N'Biển nào báo hiệu “Đường hai chiều”?','CAU141',2),
(N'Biển nào báo hiệu “Giao nhau với đường hai chiều”?','CAU142',2),
(N'Biển nào báo hiệu “Chú ý chướng ngại vật”?','CAU143',2),
(N'Gặp biển nào người tham gia giao thông phải đi chậm và thận trọng đề phòng khả năng xuất hiện và di chuyển bất ngờ của trẻ em trên mặt đường?','CAU144',2),
(N'Biển nào chỉ dẫn nơi bắt đầu đoạn đường dành cho người đi bộ?','CAU145',2),
(N'Biển báo này có ý nghĩa gì?','CAU146',2),
(N'Biển nào (đặt trước ngã ba, ngã tư) cho phép xe được rẽ sang hướng khác?','CAU147',2),
(N'Biển nào báo hiệu “Hướng đi thẳng phải theo”?','CAU148',2),
(N'Biển nào báo hiệu “Đường một chiều”?','CAU149',2),
(N'Trong các biển dưới đây biển nào là biển “Hết tốc độ tối đa cho phép”?','CAU150',2),
(N'Hiệu lực của biển “Tốc độ tối đa cho phép” hết tác dụng khi gặp biển nào dưới đây?','CAU151',2),
(N'Trong các biển dưới đây biển nào là biển “Hết tốc độ tối thiểu”?','CAU152',2),
(N'Biển nào dưới đây báo hiệu hết cấm vượt?','CAU153',2),
(N'Trong các biển dưới đây biển nào là biển “Hết mọi lệnh cấm”?','CAU154',2),
(N'Biển nào chỉ dẫn cho người đi bộ sử dụng cầu vượt qua đường?','CAU155',2),
(N'Biển nào chỉ dẫn cho người đi bộ sử dụng hầm chui qua đường?','CAU156',2),
(N'Biển nào báo hiệu “Nơi đỗ xe dành cho người khuyết tật”?','CAU157',2),
(N'Gặp biển báo này, người tham gia giao thông phải xử lý như thế nào?','CAU158',2),
(N'Biển số 1 có ý nghĩa gì?','CAU159',2),
(N'Vạch kẻ đường nào dưới đây là vạch phân chia các làn xe cùng chiều?','CAU160',2),
(N'Vạch kẻ đường nào dưới đây là vạch phân chia hai chiều xe chạy (vạch tim đường), xe không được lấn làn, không được đè lên vạch?','CAU161',2),
(N'Vạch kẻ đường nào dưới đây là vạch phân chia hai chiều xe chạy (vạch tim đường)?','CAU162',2),
(N' Các vạch dưới đây có tác dụng gì?','CAU163',2),
(N'Khi gặp vạch kẻ đường nào các xe được phép đè vạch?','CAU164',2),
(N'Vạch dưới đây có ý nghĩa gì?','CAU165',2),
(N'Thứ tự các xe đi như thế nào là đúng quy tắc giao thông?','CAU166',2),
(N'Thứ tự các xe đi như thế nào là đúng quy tắc giao thông?','CAU167',2),
(N'Trường hợp này xe nào được quyền đi trước?','CAU168',2),
(N'Xe nào được quyền đi trước trong trường hợp này?','CAU169',2),
(N'Theo tín hiệu đèn, xe nào được phép đi?','CAU170',2),
(N'Các xe đi theo hướng mũi tên, xe nào vi phạm quy tắc giao thông?','CAU171',2),
(N'Thứ tự các xe đi như thế nào là đúng quy tắc giao thông?','CAU172',2),
(N'Trong trường hợp này xe nào đỗ vi phạm quy tắc giao thông?','CAU173',2),
(N'Theo hướng mũi tên, những hướng nào xe gắn máy đi được?','CAU174',2),
(N'Xe nào đỗ vi phạm quy tắc giao thông?','CAU175',2),
(N'Xe nào đỗ vi phạm quy tắc giao thông?','CAU176',2),
(N'Xe tải kéo mô tô ba bánh như hình này có đúng quy tắc giao thông không?','CAU177',2),
(N'Xe nào được quyền đi trước trong trường hợp này?','CAU178',2),
(N'Thứ tự các xe đi như thế nào là đúng quy tắc giao thông?','CAU179',2),
(N'Xe nào được quyền đi trước trong trường hợp này?','CAU180',2),
(N'Xe nào vi phạm quy tắc giao thông?','CAU181',2),
(N'Các xe đi như thế nào là đúng quy tắc giao thông?','CAU182',2),
(N'Theo hướng mũi tên, xe nào được phép đi?','CAU183',2),
(N'Trong hình dưới đây, xe nào chấp hành đúng quy tắc giao thông?','CAU184',2),
(N'Theo hướng mũi tên, những hướng nào xe mô tô được phép đi?','CAU185',2),
(N'Trong trường hợp này, thứ tự xe đi như thế nào là đúng quy tắc giao thông?','CAU186',2),
(N'Trong hình dưới, những xe nào vi phạm quy tắc giao thông?','CAU187',2),
(N'Trong hình dưới, những xe nào vi phạm quy tắc giao thông?','CAU188',2),
(N'Bạn có được phép vượt xe mô tô phía trước không?','CAU189',2),
(N'Theo tín hiệu đèn của xe cơ giới, xe nào vi phạm quy tắc giao thông?','CAU190',2),
(N'Các xe đi theo hướng mũi tên, xe nào vi phạm quy tắc giao thông?','CAU191',2),
(N'Các xe đi theo hướng mũi tên, xe nào vi phạm quy tắc giao thông?','CAU192',2),
(N'Các xe đi theo hướng mũi tên, xe nào vi phạm quy tắc giao thông?','CAU193',2),
(N' Các xe đi theo hướng mũi tên, xe nào chấp hành đúng quy tắc giao thông?','CAU194',2),
(N'Các xe đi theo thứ tự nào là đúng quy tắc giao thông đường bộ?','CAU195',2),
(N'Các xe đi theo thứ tự nào là đúng quy tắc giao thông đường bộ?','CAU196',2),
(N'Bạn xử lý như thế nào trong trường hợp này?','CAU197',2),
(N'Xe nào dừng đúng theo quy tắc giao thông?','CAU198',2),
(N'Xe của bạn đang di chuyển gần đến khu vực giao cắt với đường sắt, khi rào chắn đang dịch chuyển, bạn điều khiển xe như thế nào là đúng quy tắc giao thông?','CAU199',2),
(N'Trong tình huống dưới đây, xa đầu kéo kéo rơ moóc (xe container) đang rẽ phải, xe con màu xanh và xe máy phía sau xe container đi như thế nào để đảm bảo an toàn?','CAU200',2)


-- CHÈN DỮ LIỆU VÀO BẢNG DAPAN
DELETE FROM DAPAN
INSERT INTO DBO.DAPAN (NOIDUNG,TRANGTHAI,GIAITHICH,ID_CAUHOI) VALUES
(N'Phần mặt đường và lề đường.',0,'',1),
(N'Phần đường xe chạy.',1,N'Giải thích: Phần đường xe chạy là phần của đường bộ được sử dụng cho phương tiện giao thông qua lại.',1),
(N'Phần đường xe cơ giới.',0,'',1),
(N'Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, sử dụng cho xe chạy.',0,'',2),
(N'Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.',1,N'Giải thích: Làn đường có bề rộng đủ cho xe chạy an toàn.',2),
(N'Là đường cho xe ô tô chạy, dừng, đỗ an toàn.',0,'',2),
(N'Là bộ phận của đường để ngăn cách không cho các loại xe vào những nơi không được phép.',0,'',3),
(N'Là bộ phận của đường để phân tách phần đường xe chạy và hành lang an toàn giao thông.',0,'',3),
(N'Là bộ phận của đường để phân chia mặt đường thành hai chiều xe chạy riêng biệt hoặc để phân chia phần đường của xe cơ giới và xe thô sơ.',1,N'Giải thích: Dải phân cách phân chia mặt đường thành hai chiều xe chạy riêng biệt.',3),
(N'Dải phân cách gồm loại cố định và loại di động.',1,N'Giải thích: Dải phân cách gồm cố định và di động.',4),
(N'Dải phân cách gồm tường chống ồn, hộ lan cứng và hộ lan mềm.',0,'',4),
(N'Dải phân cách gồm giá long môn và biển báo hiệu đường bộ.',0,'',4),
(N'Là người điều khiển xe cơ giới.',1,N'Giải thích: Người lái xe là người điều khiển xe cơ giới.',5),
(N'Là người điều khiển xe thô sơ.',0,'',5),
(N'Là người điều khiển xe có súc vật kéo.',0,'',5),
(N'Đường không ưu tiên',0,'',6),
(N'Đường tỉnh lộ.',0,'',6),
(N'Đường ưu tiên',1,N'Giải thích: Đường ưu tiên được nhường đường khi qua nơi giao nhau.',6),
(N'Gồm xe ô tô; máy kéo; xe mô tô hai bánh; xe mô tô ba bánh; xe gắn máy; xe cơ giới dùng cho người khuyết tật và xe máy chuyên dùng.',0,'',7),
(N'Gồm ô tô; máy kéo; rơ moóc hoặc sơ mi rơ moóc được kéo bởi xe ô tô, máy kéo; xe mô tô hai bánh; xe mô tô ba bánh, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự.',1,N'Giải thích: Phương tiện giao thông cơ giới không có xe máy chuyên dùng.',7),
(N'Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe xích lô, xe lăn dùng cho người khuyết tật, xe súc vật kéo và các loại xe tương tự.',1,N'Giải thích: Phương tiện giao thông thô sơ không có xe máy chuyên dùng; xe ô tô.',8),
(N'Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe gắn máy, xe cơ giới dùng cho người khuyết tật và xe máy chuyên dùng.',0,'',8),
(N'Gồm xe ô tô, máy kéo, rơ moóc hoặc sơ mi rơ moóc được kéo bởi xe ô tô, máy kéo.',0,'',8),
(N'Phương tiện giao thông cơ giới đường bộ.',0,'',9),
(N'Phương tiện giao thông thô sơ đường bộ và xe máy chuyên dùng.',0,'',9),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: Phương tiện giao thông gồm tất cả các loại phương tiện.',9),
(N'Người điều khiển, người sử dụng phương tiện tham gia giao thông đường bộ.',0,'',10),
(N'Người điều khiển, dẫn dắt súc vật; người đi bộ trên đường bộ.',0,'',10),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: Người tham gia giao thông gồm người sử dụng phương tiện và người đi bộ.',10),
(N'Người điều khiển xe cơ giới, người điều khiển xe thô sơ.',0,'',11),
(N'Người điều khiển xe máy chuyên dùng tham gia giao thông đường bộ.',0,'',11),
(N'Cả ý 1 và ý 2..',1,N'Giải thích: Người điều khiển phương tiện gồm cả xe cơ giới và xe máy chuyên dùng.',11),
(N'Là người điều khiển phương tiện tham gia giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.',0,'',12),
(N'Là cảnh sát giao thông, người được giao nhiệm vụ hướng dẫn giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.',1,N'Giải thích: Người điều khiển giao thông là cảnh sát giao thông.',12),
(N'Là người tham gia giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.',0,'',12),
(N'Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.',0,'',13),
(N'Là trạng thái đứng yên tạm thời của phương tiện giao thông trong một khoảng thời gian cần thiết đủ để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác',1,N'Giải thích: Dừng xe là đứng yên tạm thời.',13),
(N'Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian giữa 02 lần vận chuyển hàng hóa hoặc hành khách.',0,'',13),
(N'Là trạng thái đứng yên của phương tiện giao thông có thời hạn trong một khoảng thời gian cần thiết đủ để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.',0,'',14),
(N'Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian.',1,N'Giải thích: Đỗ xe là đứng yên không giới hạn thời gian.',14),
(N'Diễn ra trên đường phố không có người qua lại.',0,'',15),
(N'Được người dân ủng hộ.',0,'',15),
(N'Được cơ quan có thẩm quyền cấp phép.',1,N'Giải thích: Cuộc đua xe cần cấp phép.',15),
(N'Bị nghiêm cấm.',1,N'Giải thích: Có ma tuý bị nghiêm cấm.',16),
(N'Không bị nghiêm cấm.',0,'',16),
(N'Không bị nghiêm cấm, nếu có chất ma túy ở mức nhẹ, có thể điều khiển phương tiện tham gia giao thông.',0,'',16),
(N'Chỉ bị nhắc nhở.',0,'',17),
(N'Bị xử phạt hành chính hoặc có thể bị xử lý hình sự tùy theo mức độ vi phạm.',1,N'Giải thích: Sử dụng rượu, bia khi lái xe bị phạt hành chính hoặc xử lý hình sự.',17),
(N'Không bị xử lý hình sự.',0,'',17),
(N'Người điều khiển: Xe ô tô, xe mô tô, xe đạp, xe gắn máy.',1,N'Giải thích: Người điều khiển bị cấm sử dụng rượu, bia khi tham gia giao thông.',18),
(N'Người ngồi phía sau người điều khiển xe cơ giới.',0,'',18),
(N'Người đi bộ.',0,'',18),
(N'Bị nghiêm cấm tùy trường hợp.',0,'',19),
(N'Không bị nghiêm cấm.',0,'',19),
(N'Bị nghiêm cấm.',1,'',19),
(N'Từ 22 giờ đêm đến 5 giờ sáng.',0,'',20),
(N'Từ 5 giờ sáng đến 22 giờ tối.',1,N'Giải thích: Chỉ sử dụng còi từ 5 giời sáng đến 22 giờ tối.',20),
(N'Từ 23 giờ đêm đến 5 giờ sáng hôm sau.',0,'',20),
(N'Bất cứ đèn nào miễn là mắt nhìn rõ phía trước.',0,'',21),
(N'Chỉ bật đèn chiếu xa (đèn pha) khi không nhìn rõ đường.',0,'',21),
(N'Đèn chiếu gần (đèn cốt).',1,N'Giải thích: Trong đô thị sử dụng đèn chiếu gần.',21),
(N'Phải đảm bảo phụ tùng do đúng nhà sản xuất đó cung cấp.',0,'',22),
(N'Phải được chấp thuận của cơ quan có thẩm quyền.',1,N'Giải thích: Lắp đặt còi đèn không đúng thiết kế phải được chấp thuận của cơ quan có thẩm quyền.',22),
(N'Phải là xe đăng ký và hoạt động tại các khu vực có địa hình phức tạp.',0,'',22),
(N'Được phép.',0,'',23),
(N'Không được phép.',1,N'Giải thích: Không được phép quay đầu xe ở phần đường dành cho người đi bộ qua đường.',23),
(N'Tùy từng trường hợp.',0,'',23),
(N'Không được vượt.',0,'',24),
(N'Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông.',0,'',24),
(N'Được vượt khi đảm bảo an toàn.',1,N'Giải thích: Được vượt khi xe không phát tín hiệu ưu tiên.',24),
(N'Không được vượt.',1,N'Giải thích: Không được vượt khi đang phát tín hiệu ưu tiên.',25),
(N'Được vượt khi đang đi trên cầu.',0,'',25),
(N'Được vượt khi đảm bảo an toàn.',0,'',25),
(N'Được phép.',0,'',26),
(N'Tùy trường hợp.',0,'',26),
(N'Không được phép.',1,'',26),
(N'Được phép.',0,'',27),
(N'Tùy trường hợp.',0,'',27),
(N'Không được phép.',1,'',27),
(N'Buông cả hai tay; sử dụng xe để kéo, đẩy xe khác, vật khác; sử dụng chân chống của xe quệt xuống đường khi xe đang chạy.',1,'',28),
(N'Buông một tay; sử dụng xe để chở người hoặc hàng hóa; để chân chạm xuống đất khi khởi hành.',0,'',28),
(N'Chở người ngồi sau dưới 16 tuổi.',0,'',28),
(N'Được mang, vác tùy trường hợp cụ thể.',0,'',29),
(N'Không được mang, vác.',1,N'Giải thích: Xe mô tô không được mang vác vật cồng kềnh.',29),
(N'ược mang, vác tùy theo sức khỏe của bản thân.',0,'',29),
(N'Được phép.',0,'',30),
(N'Được bám trong trường hợp phương tiện của mình bị hỏng.',0,'',30),
(N'Không được phép.',1,N'Giải thích: Xe mô tô không được kéo xe khác.',30),
(N'Được sử dụng.',0,'',31),
(N'Chỉ người ngồi sau được sử dụng.',0,'',31),
(N'Không được sử dụng.',1,N'Giải thích: Không được sử dụng ô.',31),
(N'Chỉ được phép nếu cả hai đội mũ bảo hiểm.',0,'',32),
(N'Không được phép.',1,N'Giải thích: Xe mô tô không được kéo xe khác.',32),
(N'Chỉ được thực hiện trên đường thật vắng.',0,'',32),
(N'Chỉ được kéo nếu đã nhìn thấy trạm xăng.',0,'',33),
(N'Chỉ được thực hiện trên đường vắng phương tiện cùng tham gia giao thông.',0,'',33),
(N'Không được phép.',1,N'Giải thích: Xe mô tô không được kéo xe khác.',33),
(N'Không được vận chuyển.',1,N'Giải thích: Xe mô tô không được mang vác vật cồng kềnh.',34),
(N'Chỉ được vận chuyển khi đã chằng buộc cẩn thận.',0,'',34),
(N'Chỉ được vận chuyển vật cồng kềnh trên xe máy nếu khoảng cách về nhà ngắn hơn 2 km.',0,'',34),
(N'16 tuổi.',0,'',35),
(N'18 tuổi.',1,N'Giải thích: Độ tuổi lấy bằng theo hạng (cách nhau 3 tuổi): 16: Xe dưới 50cm3; 18: Hạng A, B1, B2; 21: Hạng C, FB; 24: Hạng D, FC; 27: Hạng E, FD.',35),
(N'17 tuổi.',0,'',35),
(N'Xe mô tô 2 bánh có dung tích xi lanh từ 50 cm3 trở lên.',0,'',36),
(N'Xe gắn máy có dung tích xi lanh dưới 50 cm3.',1,N'Giải thích: Độ tuổi lấy bằng theo hạng (cách nhau 3 tuổi): 16: Xe dưới 50cm3; 18: Hạng A, B1, B2; 21: Hạng C, FB; 24: Hạng D, FC; 27: Hạng E, FD.',36),
(N'Xe ô tô tải dưới 3,5 tấn; xe chở người đến 9 chỗ ngồi.',0,'',36),
(N'Xe mô tô có dung tích xi lanh 125 cm3.',0,'',37),
(N'Xe mô tô có dung tích xi lanh từ 175 cm3 trở lên.',1,N'iải thích: A1 mô tô dưới 175cm3 và xe 3 bánh của người khuyết tật; A2 mô tô 175cm3 trở lên; A3 xe 3 bánh.',37),
(N'Xe mô tô có dung tích xi lanh 100 cm3.',0,'',37),
(N'Xe mô tô hai bánh có dung tích xi lanh từ 50 cm3 đến dưới 175 cm3.',0,'',38),
(N'Xe mô tô ba bánh dùng cho người khuyết tật.',0,'',38),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: A1 mô tô dưới 175cm3 và xe 3 bánh của người khuyết tật; A2 mô tô 175cm3 trở lên; A3 xe 3 bánh.',38),
(N'Biển báo nguy hiểm.',0,'',39),
(N'Biển báo cấm.',1,N'Giải thích: Biển cấm: vòng tròn đỏ.',39),
(N'Biển báo chỉ dẫn.',0,'',39),
(N'Biển báo nguy hiểm.',1,N'Giải thích: Biển nguy hiểm: Hình tam giác vàng.',40),
(N'Biển báo cấm.',0,'',40),
(N'Biển báo hiệu lệnh.',0,'',40),
(N'Biển báo nguy hiểm.',0,'',41),
(N'Biển báo cấm.',0,'',41),
(N'Biển báo hiệu lệnh phải thi hành.',1,N'Giải thích: Biển hiệu lệnh: Vòng tròn xanh.',41),
(N'Biển báo nguy hiểm.',0,'',42),
(N'Biển báo cấm.',0,'',42),
(N'Biển báo chỉ dẫn.',1,N'Giải thích: Biển chỉ dẫn: Hình vuông hoặc hình chữ nhật xanh',42),
(N'02 năm.',0,'',43),
(N'03 năm.',0,'',43),
(N'05 năm.',1,N'Giải thích: 05 năm không cấp lại nếu sử dụng bằng lái đã khai báo mất.',43),
(N'Người tham gia giao thông ở các hướng phải dừng lại.',0,'',44),
(N'Người tham gia giao thông ở các hướng được đi theo chiều gậy chỉ của cảnh sát giao thông.',0,'',44),
(N'Người tham gia giao thông ở phía trước và phía sau người điều khiển phải dừng lại; người tham gia giao thông ở phía bên phải và phía bên trái người điều khiển được đi tất cả các hướng.',1,N'Giải thích: Người điều khiển giao thông tay giang ngang thì trước mặt và sau lưng dừng lại.',44),
(N'Người tham gia giao thông ở hướng đối diện cảnh sát giao thông được đi, các hướng khác cần phải dừng lại.',0,'',45),
(N'Người tham gia giao thông được rẽ phải theo chiều mũi tên màu xanh ở bục cảnh sát giao thông.',0,'',45),
(N'Người tham gia giao thông ở các hướng đều phải dừng lại trừ các xe ở trong khu vực giao nhau.',1,N'Giải thích: người điều khiển giao thông giơ tay thẳng đứng thì ở tất cả các hướng phải dừng lại.',45),
(N'Biển báo hiệu cố định.',0,'',46),
(N'Báo hiệu tạm thời.',1,N'Giải thích: ưu tiên biển báo tạm thời.',46),
(N'Cho xe đi trên bất kỳ làn đường nào hoặc giữa hai làn đường nếu không có xe phía trước; khi cần thiết phải chuyển làn đường, người lái xe phải quan sát xe phía trước để bảo đảm an toàn.',1,N'Giải thích: Chuyển làn đường phải có tín hiệu báo trước.',47),
(N'Phải cho xe đi trong một làn đường và chỉ được chuyển làn đường ở những nơi cho phép; khi chuyển làn phải có tín hiệu báo trước và phải bảo đảm an toàn.',0,'',47),
(N'Phải cho xe đi trong một làn đường, khi cần thiết phải chuyển làn đường, người lái xe phải quan sát xe phía trước để bảo đảm an toàn.',0,'',47),
(N'Xe thô sơ phải đi trên làn đường bên trái ngoài cùng, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên phải.',0,'',48),
(N'Xe thô sơ phải đi trên làn đường bên phải trong cùng, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên trái.',1,N'Giải thích: Xe thô sơ phải đi làn đường bên phải trong cùng.',48),
(N'Xe thô sơ đi trên làn đường phù hợp không gây cản trở giao thông, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên phải.',0,'',48),
(N'Phải báo hiệu bằng đèn hoặc còi.',0,'',49),
(N'Chỉ được báo hiệu bằng còi.',0,'',49),
(N'Chỉ báo hiệu bằng đèn.',1,N'Giải thích: Chỉ sử dụng còi từ 5 giờ sáng đến 22 giờ tối. Nên phải sử dụng đèn để báo hiệu.',49),
(N'Tăng tốc độ và ra hiệu cho xe sau vượt, không được gây trở ngại cho xe sau vượt.',0,N'',50),
(N'Người điều khiển phương tiện phía trước phải giảm tốc độ, đi sát về bên phải của phần đường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại cho xe sau vượt.',1,N'',50),
(N'Cho xe tránh về bên trái mình và ra hiệu cho xe sau vượt; nếu có chướng ngại vật phía trước hoặc thiếu điều kiện an toàn chưa cho vượt được phải ra hiệu cho xe sau biết; cấm gây trở ngại cho xe xin vượt.',0,N'',50),
(N'Quan sát gương, ra tín hiệu, quan sát an toàn và chuyển hướng.',0,N'',51),
(N'Quan sát gương, giảm tốc độ, ra tín hiệu chuyển hướng, quan sát an toàn và chuyển hướng.',1,N'Giải thích: Chuyển hướng phải giảm tốc độ.',51),
(N'Quan sát gương, tăng tốc độ, ra tín hiệu và chuyển hướng.',0,N'',51),
(N'Nơi đường hẹp chỉ đủ cho một xe chạy và có chỗ tránh xe thì xe nào ở gần chỗ tránh hơn phải vào vị trí tránh, nhường đường cho xe kia đi.',0,N'',52),
(N'Xe xuống dốc phải nhường đường cho xe đang lên dốc; xe nào có chướng ngại vật phía trước phải nhường đường cho xe không có chướng ngại vật đi trước.',0,N'',52),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: Tránh xe ngược chiều thì nhường đường qua đường hẹp và nhường xe lên dốc.',52),
(N'Tiếp tục đi vì xe lên dốc phải nhường đường cho mình.',0,N'',53),
(N'Nhường đường cho xe lên dốc.',1,N'Giải thích: Nhường đường cho xe lên dốc.',53),
(N'Chỉ nhường đường khi xe lên dốc nháy đèn.',0,N'',53),
(N'Nhường đường cho xe đi ở bên phải mình tới.',0,N'',54),
(N'Nhường đường cho xe đi ở bên trái mình tới.',0,N'',54),
(N'Nhường đường cho xe đi trên đường ưu tiên hoặc đường chính từ bất kỳ hướng nào tới.',1,N'Giải thích: Đường không ưu tiên nhường đường cho xe trên đường ưu tiên.',54),
(N'Phải nhường đường cho xe đi đến từ bên phải.',1,N'Giải thích: Giao nhau không có vòng xuyến thì nhường xe đến từ bên phải.',55),
(N'Xe báo hiệu xin đường trước xe đó được đi trước.',0,N'',55),
(N'Phải nhường đường cho xe đi đến từ bên trái.',0,N'',55),
(N'5 mét.',1,N'Giải thích: Đứng cách ray đường sắt 5m.',56),
(N'3 mét.',0,N'',56),
(N'4 mét.',0,N'',56),
(N'Xe cơ giới, xe máy chuyên dùng phải bật đèn; xe thô sơ phải bật đèn hoặc có vật phát sáng báo hiệu; chỉ được dùng xe, đỗ xe ở nơi quy định.',1,N'Giải thích: Trong hầm chỉ đường dừng xe, đỗ xe ở nơi quy định.',57),
(N'Xe cơ giới phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.',0,N'',57),
(N'Xe máy chuyên dùng phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.',0,N'',57),
(N'Khi tham gia giao thông đường bộ.',1,N'',58),
(N'Chỉ khi đi trên đường chuyên dùng; đường cao tốc.',0,N'',58),
(N'Khi tham gia giao thông trên đường tỉnh lộ hoặc quốc lộ.',0,N'',58),
(N'Chở người bệnh đi cấp cứu; trẻ em dưới 14 tuổi.',0,N'',59),
(N'Áp giải người có hành vi vi phạm pháp luật.',0,N'',59),
(N'Cả ý 1 và ý 2.',1,N'',59),
(N'Đi vào phần đường dành cho người đi bộ và phương tiện khác; sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính), đi xe dàn hàng ngang.',1,N'Giải thích: Xe mô tô 2 bánh không được đi vào phần đường cho người đi bộ.',60),
(N'Chở 02 người; trong đó, có người bị bệnh đi cấp cứu hoặc trẻ em dưới 14 tuổi hoặc áp giải người có hành vi vi phạm pháp luật.',0,'',60),
(N'Điều khiển phương tiện tham gia giao thông trên đường tỉnh lộ hoặc quốc lộ.',0,'',60),
(N'Được phép nhưng phải đảm bảo an toàn.',0,'',61),
(N'Không được phép.',1,N'',61),
(N'Được phép tùy từng hoàn cảnh, điều kiện cụ thể.',0,'',61),
(N'Khi có báo hiệu cảnh báo nguy hiểm hoặc có chướng ngại vật trên đường; khi chuyển hướng xe chạy hoặc tầm nhìn bị hạn chế; khi qua nơi đường giao nhau, nơi đường bộ giao nhau với đường sắt; đường vòng; đường có địa hình quanh co, đèo dốc.',0,'',62),
(N'Khi qua cầu, cống hẹp; khi lên gần đỉnh dốc, khi xuống dốc, khi qua trường học, khu đông dân cư, khu vực đang thi công trên đường bộ; hiện trường xảy ra tai nạn giao thông.',0,'',62),
(N'Cả ý 1 và ý 2.',1,'',62),
(N'Nhường đường cho người đi bộ đang đi trên phần đường dành cho người đi bộ sang đường; nhường đường cho xe đi trên đường ưu tiên, đường chính từ bất kỳ hướng nào tới; nhường đường cho xe ưu tiên, xe đi từ bên phải đến.',1,N'Giải thích: Người lái xe phải nhường đường cho xe ưu tiên.',63),
(N'Nhường đường cho người đi bộ đang đứng chờ đi qua phần đường dành cho người đi bộ sang đường; nhường đường cho xe đi trên đường ngược chiều, đường nhánh từ bất kỳ hướng nào tới; nhường đường cho xe đi từ bên trái đến.',0,'',63),
(N'Không phải nhường đường.',0,'',63),
(N'Khi cho xe chạy thẳng.',0,'',64),
(N'Trước khi thay đổi làn đường.',1,N'Giải thích: Phải bật đèn tín hiệu rẽ trước khi thay đổi làn đường.',64),
(N'Sau khi thay đổi làn đường.',0,'',64),
(N'Xe bị vượt bất ngờ tăng tốc độ và cố tình không nhường đường.',0,'',65),
(N'Xe bị vượt giảm tốc độ và nhường đường.',0,'',65),
(N'Cả ý 1 và ý 2',1,N'Giải thích: Không được vượt khi xe bị vượt bất ngờ tăng tốc hoặc phát hiện có xe đi ngược chiều.',65),
(N'Nếu đủ điều kiện an toàn, người lái xe phải giảm tốc độ, đi sát về bên phải của phần đường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại đối với xe xin vượt.',1,N'Giải thích: Xử lý cho xe sau vượt thì giảm tốc độ và đi về bên phải.',66),
(N'Lái xe vào lề đường bên trái và giảm tốc độ để xe phía sau vượt qua, không được gây trở ngại đối với xe xin vượt.',0,'',66),
(N'Nếu đủ điều kiện an toàn, người lái xe phải tăng tốc độ, đi sát về bên phải của phần đường chạy cho đến khi xe sau vượt qua.',0,'',66),
(N'Phải đội mũ bảo hiểm đạt chuẩn, có cài quai đúng quy cách, mặc quần áo gọn gàng; không sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính).',1,N'',67),
(N'Phải đội mũ bảo hiểm khi trời mưa gió hoặc trời quá nắng; có thể sử dụng ô, điện thoại di động, thiết bị âm thanh nhưng phải đảm bảo an toàn.',0,'',67),
(N'Phải đội mũ bảo hiểm khi cảm thấy mất an toàn giao thông hoặc khi chuẩn bị di chuyển quãng đường xa.',0,'',67),
(N'Là đoạn đường nằm trong khu công nghiệp có đông người và phương tiện tham gia giao thông và được xác định cụ thể bằng biển chỉ dẫn địa giới.',0,'',68),
(N'Là đoạn đường bộ nằm trong khu vực nội thành phố, nội thị xã, nội thị trấn và những đoạn đường có đông dân cư sinh sống sát dọc theo đường, có các hoạt động ảnh hưởng đến an toàn giao thông; được xác định bằng biển báo hiệu là đường khu đông dân cư.',1,N'Giải thích: Đường bộ trong khu vực đông dân cư được xác định bằng biển báo.',68),
(N'Là đoạn đường nằm ngoài khu vực nội thành phố, nội thị xã có đông người và phương tiện tham gia giao thông và được xác định cụ thể bằng biển chỉ dẫn địa giới.',0,'',68),
(N'50 km/h.',0,'',69),
(N'40 km/h.',1,N'Giải thích: Xe gắn máy tối đa 40km/h.',69),
(N'60 km/h.',0,'',69),
(N'60 km/h.',1,N'Giải thích: Có giải phân cách giữa thì được xem là đường đôi. Trong khu vực đông dân cư, đường đôi; đường một chiều có từ hai làn xe cơ giới trở lên: 60km/h.',70),
(N'50 km/h.',0,N'',70),
(N'40 km/h.',0,N'',70),
(N'60 km/h.',0,N'',71),
(N'50 km/h.',1,N'Giải thích: Trong khu vực đông dân cư, đường hai chiều; đường một chiều có một làn xe cơ giới: 50km/h.',71),
(N'40 km/h.',0,N'',71),
(N'Ô tô con, ô tô tải, ô tô chỏ người trên 30 chỗ.',1,N'Giải thích: Xe cơ giới không bao gồm xe gắn máy. Trong khu vực đông dân cư, đường hai chiều; đường một chiều có một làn xe cơ giới: 50km/h.',72),
(N'Xe gắn máy, xe máy chuyên dùng.',0,N'',72),
(N'Cả ý 1 và ý 2.',0,N'',72),
(N'Chủ động giữ khoảng cách an toàn phù hợp với xe chạy liền trước xe của mình.',0,N'',73),
(N'Đảm bảo khoảng cách an toàn theo mật độ phương tiện, tình hình giao thông thực tế.',0,N'',73),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: Khoảng cách an toàn dưới 60km/h: Chủ động và đảm bảo khoảng cách.',73),
(N'Gặp biển báo nguy hiểm trên đường.',1,N'Giải thích: Giảm tốc độ, chú ý quan sát khi gặp biển báo nguy hiểm.',74),
(N'Gặp biển chỉ dẫn trên đường.',0,N'',74),
(N'Gặp biển báo hết mọi lệnh cấm.',0,N'',74),
(N'Hiệu lệnh của nhân viên gác chắn.',0,N'',75),
(N'Đèn đỏ sáng nháy, cờ đỏ, biển đỏ.',0,N'',75),
(N'Tất cả các ý trên.',1,N'',75),
(N'Để làm đẹp.',0,N'',76),
(N'Để tránh mưa nắng.',0,N'',76),
(N'Để giảm thiểu chấn thương vùng đầu.',1,N'',76),
(N'Tăng tốc độ qua đường giao nhau để đi trước xe đi trên đường ưu tiên.',0,N'',77),
(N'Giảm tốc độ qua đường giao nhau để đi trước xe đi trên đường ưu tiên.',0,N'',77),
(N'Nhường đường cho xe đi trên ưu tiên từ bất kỳ hướng nào tới.',1,N'Giải thích: Đứng cách ray đường sắt 5m.',77),
(N'Giảm tốc độ, đi từ từ để vượt qua trước người đi bộ.',0,N'',78),
(N'Giảm tốc độ, có thể dừng lại nếu cần thiết trước vạch dừng xe để nhường đường cho người đi bộ qua đường.',1,N'Giải thích: Nơi có vạch kẻ đường dành cho người đi bộ thì nhường đường.',78),
(N'Tăng tốc độ để vượt qua trước người đi bộ.',0,N'',78),
(N'Đỏ – Vàng – Xanh.',1,N'',79),
(N'Cam – Vàng – Xanh.',0,N'',79),
(N'Vàng – Xanh dương – Xanh lá.',0,N'',79),
(N'Phải cho xe dừng lại trước vạch dừng, trường hợp đã đi quá vạch dừng hoặc đã quá gần vạch dừng nếu dừng lại thấy nguy hiểm thì được đi tiếp.',0,N'',80),
(N'Trong trường hợp tín hiệu vàng nhấp nháy là được đi nhưng phải giảm tốc độ, chú ý quan sát nhường đường cho người đi bộ qua đường.',0,N'',80),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: Đèn vàng dừng lại trước vạch dừng hoặc nhấp nháy thì đi chậm.',80),
(N'Ra tín hiệu bằng tay rồi cho xe vượt qua.',0,N'',81),
(N'Tăng ga mạnh để gây sự chú ý rồi cho xe vượt qua.',0,N'',81),
(N'Bạn phải có tín hiệu bằng đèn hoặc còi.',1,N'Giải thích: Muốn vượt xe thì phải báo hiệu bằng đèn hoặc còi.',81),
(N'Đường ướt, đường có sỏi cát trên nền đường.',0,N'',82),
(N'Đường hẹp có nhiều điểm giao cắt từ hai phía.',0,N'',82),
(N'Tất cả các ý nêu trên.',1,N'Giải thích: Giảm tốc độ trên đường ướt, đường hẹp và đèo dốc.',82),
(N'Tăng tốc độ để nhanh chóng vượt qua bến đỗ.',0,N'',83),
(N'Giảm tốc độ đến mức an toàn có thể và quan sát người qua đường và từ từ vượt qua xe buýt.',1,N'Giải thích: Xe buýt đang dừng đón trả khách thì giảm tốc độ và từ từ vượt qua xe buýt.',83),
(N'Yêu cầu phải dừng lại phía sau xe buýt chờ xe rời bến mới đi tiếp.',0,N'',83),
(N'Là sự hiểu biết và chấp hành nghiêm chỉnh pháp luật về giao thông; là ý thức trách nhiệm với cộng đồng khi tham gia giao thông.',0,N'',84),
(N'Là ứng xử có văn hóa, có tình yêu thương con người trong các tình huống không may xảy ra khi tham gia giao thông.',0,N'',84),
(N'Cả ý 1 và ý 2.',1,N'',84),
(N'Điều khiển xe đi bên phải theo chiều đi của mình; đi đúng phần đường, làn đường quy định; đội mũ bảo hiểm đạt chuẩn, cài quai đúng quy định.',1,N'',85),
(N'Điều khiển xe đi trên phần đường, làn đường có ít phương tiện tham gia giao thông.',0,N'',85),
(N'Điều khiển xe và đội mũ bảo hiểm ở nơi có biển báo bắt buộc đội mũ bảo hiểm.',0,N'',85),
(N'Điều khiển xe đi bên phải theo chiều đi của mình; đi đúng phần đường, làn đường quy định; dừng, đỗ xe đúng nơi quy định; đã uống rượu, bia thì không lái xe.',1,N'',86),
(N'Điều khiển xe đi trên phần đường, làn đường có ít phương tiện giao thông; dừng xe, đỗ xe ở nơi thuận tiện hoặc theo yêu cầu của hành khách, của người thân.',0,N'',86),
(N'Dừng và đỗ xe ở nơi thuận tiện cho việc chuyên chở hành khách và giao nhận hàng hóa; sử dụng ít rượu, bia thì có thể lái xe.',0,N'',86),
(N'Thực hiện sơ cứu ban đầu trong trường hợp khẩn cấp; thông báo vụ tai nạn đến cơ quan thi hành pháp luật.',1,N'',87),
(N'Nhanh chóng lái xe gây tai nạn hoặc đi nhờ xe khác ra khỏi hiện tượng vụ tai nạn.',0,N'',87),
(N'Cả ý 1 và ý 2.',0,N'',87),
(N'Bấm còi liên tục thúc giục các phương tiện phía trước nhường đường.',0,N'',88),
(N'Đi lên vỉa hè, tận dùng mọi khoảng trống để nhanh chóng thoát khỏi nơi ùn tắc.',0,N'',88),
(N'Tất cả các ý nêu trên.',1,N'',88),
(N'Giữ tay ga ở mức độ phù hợp, sử dụng phanh trước và phanh sau để giảm tốc độ.',1,N'Giải thích: Xe mô tô xuống dốc dài cần sử dụng cả phanh trước và phanh sau để giảm tốc độ.',89),
(N'Nhả hết tay ga, tắt động cơ, sử dụng phanh trước và phanh sau để giảm tốc độ.',0,N'',89),
(N'Sử dụng phanh trước để giảm tốc độ kết hợp tắt chìa khóa điện của xe.',0,N'',89),
(N'Quan sát biển báo hiệu để biết nơi được phép quay đầu; quan sát kỹ địa hình nơi chọn để quay đầu; lựa chọn quỹ đạo quay đầu xe cho thích hợp; quay đầu xe với tốc độ thấp; thường xuyên báo tín hiệu để người, các phương tiện xung quanh được biết; nếu quay đầu xe ở nơi nguy hiểm thì đưa đầu xe về phía nguy hiểm đưa đuôi xe về phía an toàn.',1,N'Giải thích: Thực hiện quay đầu xe với tốc độ thấp.',90),
(N'Quan sát biển báo hiệu để biết nơi được phép quay đầu; quan sát kỹ địa hình nơi chọn để quay đầu; lựa chọn quỹ đạo quay đầu xe; quay đầu xe với tốc độ tối đa; thường xuyên báo tín hiệu để người, các phương tiện xung quanh được biết; nếu quay đầu xe ở nơi nguy hiểm thì đưa đuôi xe về phía nguy hiểm và đầu xe về phía an toàn.',0,N'',90),
(N'Không nên đi cố vào đường hẹp; xe đi ở phía sườn núi nên dừng lại trước để nhường đường; khi dừng xe nhường đường phải đỗ ngay ngắn.',0,N'',91),
(N'Trong khi tránh nhau không nơi đổi số; khi tránh nhau ban đêm, phải tắt đèn pha bật đèn cốt.',0,N'',91),
(N'Cả ý 1 và ý 2.',1,N'Giải thích: Cả ý 1 và 2 đều đúng. Ý 3 tránh nhau ban đêm bật đèn pha là sai.',91),
(N'Quan sát cẩn thận các chướng ngại vật và báo hiệu bằng còi, đèn; giảm tốc độ tới mức cần thiết, về số thấp và thực hiện quay vòng với tốc độ phù hợp với bán kính cong của đường vòng.',1,N'Giải thích: Điều khiển xe trên đường vòng cần giảm tốc độ.',92),
(N'Quan sát cẩn thận các chướng ngại vật và báo hiệu bằng còi, đèn; tăng tốc để nhanh chóng qua đường vòng và giảm tốc độ sau khi qua đường vòng.',0,N'',92),
(N'Giảm hết ga; sử dụng đồng thời cả phanh sau và phanh trước.',1,N'Giải thích: Khi phanh xe mô tô thì giảm hết ga.',93),
(N'Sử dụng phanh trước.',0,N'',93),
(N'Sử dụng phanh sau.',0,N'',93),
(N'Giảm tốc độ để đảm bảo an toàn với xe phía trước và sử dụng điện thoại để liên lạc.',0,N'',94),
(N'Giảm tốc độ để dừng xe ở nơi cho phép dừng xe sau đó sử dụng điện thoại để liên lạc.',1,N'GIải thích: Khi cần nghe điện thoại thì giảm tốc độ và dừng xe ở nơi cho phép dừng xe.',94),
(N'Tăng tốc độ để cách xa xe phía sau và sử dụng điện thoại để liên lạc.',0,N'',94),
(N'Sử dụng còi.',0,N'',95),
(N'Phanh đồng thời cả phanh trước và phanh sau.',0,N'',95),
(N'Chỉ sử dụng phanh trước.',1,N'Giải thích: Xe mô tô tay ga chỉ sử dụng phanh trước thì rất nguy hiểm.',95),
(N'Bật tín hiệu báo rẽ trước khi quay đầu, từ từ giảm tốc độ đến mức có thể dừng lại.',0,N'',96),
(N'Chỉ quay đầu xe ở những nơi được phép quay đầu.',0,N'',96),
(N'Tất cả các ý nêu trên.',1,N'',96),
(N'Để điều khiển xe chạy về phía trước.',0,N'',97),
(N'Để điều tiết công suất động cơ qua đó điều khiển tốc độ của xe.',0,N'',97),
(N'Cả ý 1 và ý 2.',1,N'',97),
(N'Để quan sát an toàn phía bên trái khi chuẩn bị rẽ trái.',0,N'',98),
(N'Để quan sát an toàn phía bên phải khi chuẩn bị rẽ phải.',0,N'',98),
(N'Để quan sát an toàn phía sau cả bên trái và bên phải trước khi chuyển hướng.',1,N'',98),
(N'Tăng ga thật nhanh, giảm ga từ từ.',0,N'',99),
(N'Tăng ga thật nhanh, giảm ga thật nhanh.',0,N'',99),
(N'Tăng ga từ từ, giảm ga thật nhanh.',1,N'',99),
(N'Đứng thẳng trên giá gác chân lái sau đó hơi gập đầu gối và khuỷu tay, đi chậm để không nẩy quá mạnh.',1,N'',100),
(N'Ngồi lùi lại phía sau, tăng ga vượt nhanh qua đoạn đường xóc.',0,N'',100),
(N'Ngồi lệch sang bên trái hoặc bên phải để lấy thăng bằng qua đoạn đường gồ ghề.',0,N'',100),
(N'Biển 1.',0,N'',101),
(N'Biển 2.',0,N'',101),
(N'Cả hai biển.',1,N'',101),
(N'Biển 1.',1,N'',102),
(N'Biển 2.',0,N'',102),
(N'Biển 3.',0,N'',102),
(N'Không biển nào.',0,N'',103),
(N'Biển 2 và 3.',1,N'',103),
(N'Biển 1 và 2.',0,N'',103),
(N'Biển 1.',0,N'',104),
(N'Biển 2.',1,N'',104),
(N'Không biển nào.',0,N'',104),
(N'Biển 1.',1,N'',105),
(N'Biển 2.',0,N'',105),
(N'Cả hai biển.',0,N'',105),
(N'Biển 1.',0,N'',106),
(N'Biển 2.',1,N'',106),
(N'Không biển nào.',0,N'',106),
(N'Biển 1 và 2.',1,N'',107),
(N'Biển 1 và 3.',0,N'',107),
(N'Biển 2 và 3.',0,N'',107),
(N'Biển 1 và 2.',1,N'',108),
(N'Biển 1 và 3.',0,N'',108),
(N'Cả ba biển.',0,N'',108),
(N'Biển 1.',0,N'',109),
(N'Biển 2.',1,N'',109),
(N'Không biển nào.',0,N'',109),
(N'Biển 1.',1,N'',110),
(N'Biển 2.',0,N'',110),
(N'Cả hai biển.',0,N'',110),
(N'Biển 1.',1,N'',111),
(N'Biển 2.',0,N'',111),
(N'Cả hai biển.',0,N'',111),
(N'Biển 1.',0,N'',112),
(N'Biển 2.',1,N'',112),
(N'Cả ba biển.',0,N'',112),
(N'Biển 1.',0,N'',113),
(N'Biển 2.',0,N'',113),
(N'Biển 1 và 2.',0,N'',113),
(N'Biển 1.',0,N'',114),
(N'Biển 2.',1,N'Biển 2: R.122 “Dừng lại” áp dụng với cả xe ưu tiên;',114),
(N'Cả ba biển.',0,N'',114),
(N'Biển 1.',1,N'P.101 “Đườn cấm” không cấm xe ưu tiên;',115),
(N'Biển 2.',0,N'',115),
(N'Cả hai biển.',0,N'',115),
(N'Biển 1.',0,N'',116),
(N'Biển 2.',0,N'',116),
(N'Biển 1 và biển 2.',1,N'',116),
(N'Biển 1.',0,N'',117),
(N'Biển 2.',0,N'',117),
(N'Biển 3.',1,N'',117),
(N'Tốc độ tối đa cho phép về ban đêm cho các phương tiện là 70 km/h.',1,N'',118),
(N'Tốc độ tối thiểu cho phép về ban đêm cho các phương tiện là 70 km/h.',0,N'',118),
(N'Được phép.',0,N'',119),
(N'Không được phép.',1,N'Giải thích: Biển phụ là biển S.501 “Phạm vi tác dụng của biển” xác định chiều dài áp dụng biển chính từ nơi đặt biển.',119),
(N'Biển 1 và 2.',0,N'',120),
(N'Biển 1 và 3.',1,N'',120),
(N'Biển 2 và 3.',0,N'',120),
(N'Biển 1.',0,N'',121),
(N'Biển 2.',1,N'',121),
(N'Biển 3.',0,N'',121),
(N'Biển 1.',1,N'',122),
(N'Biển 2.',0,N'',122),
(N'Biển 1.',1,N'Giải thích: Biển 1: W.224 “Đường người đi bộ cắt ngang”;',123),
(N'Biển 2.',0,N'',123),
(N'Biển 3.',0,N'',123),
(N'Biển 1.',0,N'',124),
(N'Cả ba biển.',0,N'',124),
(N'Biển 3.',1,N'Biển 3 báo đường dành cho người đi bộ nên phương tiện khác không được đi vào.',124),
(N'Biển 1.',1,N'',125),
(N'Biển 2.',0,N'',125),
(N'Biển 3.',0,N'',125),
(N'Biển 1.',0,N'',126),
(N'Biển 2 và 3.',0,N'',126),
(N'Cả ba biển.',1,N'Giải thích: Biển 1: W.210 “Giao nhau với đường sắt có rào chắn”; Biển : W.208 “Giao nhau với đường ưu tiên”; Biển 3: W209 “Giao nhau có tín hiệu đèn”',126),
(N'Biển 1.',1,N'',127),
(N'Biển 2 và 3.',0,N'',127),
(N'Biển 3.',0,N'',127),
(N'Biển 1.',0,N'',128),
(N'Biển 2.',0,N'',128),
(N'Biển 3.',1,N'',128),
(N'Biển 1 và 2.',0,N'',129),
(N'Biển 1 và 3.',1,N'Giải thích: Biển 1: W.210 “Giao nhau với đường sắt có rào chắn”; Biển 2: W.234 “Giao nhau với đường 2 chiều”; Biển 3: W.242a “Nơi đường sắt giao vuông gốc với đường bộ”.',129),
(N'Biển 2 và 3.',0,N'',129),
(N'Biển 1 và 2.',0,N'',130),
(N'Biển 1 và 3.',0,N'',130),
(N'Biển 2 và 3.',1,N'Giải thích: Biển 1: W.210 “Giao nhau với đường sắt có rào chắn”; Biển 2: W.211a “Giao nhau với đường sắt không có rào chắn”;
Biển 3: W.242a “Nơi đường sắt giao vuông gốc với đường bộ” ổ sung cho biển W.211a. Nên cả 2 biển 2 và 3 đều đúng.',130),
(N'Biển 1.',1,N'Giải thích: Biển 211a Giao nhau với đường sắt không có rào chắn.
Biển 2: Biển 208 Giao nhau với đường ưu tiên. 
Biển 3: Biển 211b Giao nhau với tàu điện.',131),
(N'Biển 2.',0,N'',131),
(N'Biển 3.',0,N'',131),
(N'Biển 1 và 2.',0,N'',132),
(N'Biển 1 và 3.',1,N'Giải thích: Biển 1: W.207a “Giao nhau với đường không ưu tiên”;
Biển 2: W.208 “Giao nhau với đường ưu tiên”;
Biển 3: I.401 “Bắt đầu đường ưu tiên”. Nên biến 1 và Biển 3 là đáp án đúng.',132),
(N'Biển 2 và 3.',0,N'',132),
(N'Biển 1.',1,N'Giải thích: Biển 1: W.207a “Giao nhau với đường không ưu tiên”;',133),
(N'Biển 2.',0,N'',133),
(N'Biển 3.',0,N'',133),
(N'Biển 1 và 3.',0,N'',134),
(N'Biển 2.',1,N'Biển 2: W.208 “Giao nhau với đường ưu tiên”;',134),
(N'Biển 3.',0,N'',134),
(N'Biển 1 và 2.',1,N'Giải thích: Biển 1:W.203a “Đường bị hép cả 2 bên”;
Biển 2: W.203b “Đường bị hẹp về phía trái”',135),
(N'Biển 1 và 3.',0,N'',135),
(N'Cả ba biển.',0,N'',135),
(N'Biển 1.',0,N'',136),
(N'Biển 1 và 3.',0,N'',136),
(N'Biển 2 và 3.',1,N'Giải thích: Biển 1: W.236 “Hết đường đôi; Biển 2:W.203b ‘Đường đi bị hẹp về phía trái”; Biển 2: W.203c “Đường bị hẹp về phía phải”. Câu này hỏi về việc đường bị thu hẹp nên câu tả lời đúng là Biển 2 và Biển 3.',136),
(N'Biển 1.',1,N'Giải thích: Biển 1: W.205a “Đường giao nhau cùng cấp; Biển 2: W.207a “Giao nhauvới đường không ưu tiên”; Biển 3: W.208 “Giao nhau với đường ưu tiên”.',137),
(N'Biển 2.',0,N'',137),
(N'Biển 3.',0,N'',137),
(N'Biển 1.',0,N'',138),
(N'Biển 2. ',1,N'',138),
(N'Biển 3.',0,N'',138),
(N'Biển 1.',0,N'',139),
(N'Biển 2.',0,N'',139),
(N'Biển 3.',1,N'',139),
(N'Biển 1.',1,N'',140),
(N'Biển 2.',0,N'',140),
(N'Biển 3.',0,N'',140),
(N'Biển 1.',0,N'',141),
(N'Biển 2.',1,N'',141),
(N'Biển 3.',0,N'',141),
(N'Biển 1.',0,N'',142),
(N'Biển 2.',1,N'',142),
(N'Biển 3.',0,N'',142),
(N'Biển 1.',0,N'',143),
(N'Biển 2 và 3.',1,N'',143),
(N'Cả ba biển.',0,N'',143),
(N'Biển 1.',0,N'',144),
(N'Biển 2.',1,N'',144),
(N'Biển 1.',0,N'',145),
(N'Biển 2.',1,N'Giải thích: W.224 “Đường người đi bộ cắt ngang”;
Biển 2: I.423c “Điểm bắt đầu đường đi bộ”
Biển3: W.225 “trẻ em”',145),
(N'Biển 3.',0,N'',145),
(N'Báo hiệu đường có ổ gà, lồi lõm.',0,N'',146),
(N'Báo hiệu đường có gồ giảm tốc phía trước.',1,N'Giải thích: Biển W221b “Đường có sóng mấp mô nhân tạo”.',146),
(N'Biển 1.',0,N'',147),
(N'Biển 2.',0,N'',147),
(N'Không biển nào.',1,N'Giải thích: Biển 1: R.301a “Hướng đi phải theo” chỉ được đi thẳng đặt trước ngã ba, ngã tư;
Biển 2: R.301h “Hướng đi phải theo” chỉ được rẽ trái hoặc rẽ phải đặt sau ngã ba, ngã tư;
Nên đáp án đúng là không có biển nào.',147),
(N'Biển 1.',1,N'',148),
(N'Biển 2.',0,N'',148),
(N'Biển 1.',0,N'',149),
(N'Biển 2.',0,N'',149),
(N'Cả hai biển.',1,N'Giải thích: Biển 1: R.301a “Hướng đi phải theo” chỉ được đi thẳng đặt trước ngã ba, ngã tư;
Biển 2: I.407a “Đường một chiều” không liên quan hướng đi phải theo.
Nên biển 2 là đáp án đúng.',149),
(N'Biển 1.',1,N'Giải thích:
Biển 1: DP134 “Hết hạn chế tốc độ tối đa”',150),
(N'Biển 2.',0,N'',150),
(N'Biển 3.',0,N'',150),
(N'Biển 1.',0,N'',151),
(N'Biển 3.',0,N'',151),
(N'Biển 1 và 2.',1,N'Giải thích:
Biển 1: DP134 “Hết hạn chế tốc độ tối đa”
Biển 2: DP135 “Hết mọi lệnh cấm”;
Biển 3: R307 “Hết hạn chế tốc độ tối thiểu”.
Nên Biển 1 và Biển 2 là biển “Hết hạn chế tốc độ tối đa”. Chú ý câu hỏi các biển hết hạn chế, không phải hỏi ý nghĩa của biển.',151),
(N'Biển 1.',0,N'',152),
(N'Biển 2.',0,N'',152),
(N'Biển 3.',1,N'Biển 3: R307 “Hết hạn chế tốc độ tối thiểu”.',152),
(N'Biển 1.',0,N'',153),
(N'Biển 2.',0,N'',153),
(N'Biển 2 và 3.',1,N'Biển 2: DP135 “Hết mọi lệnh cấm”;
Biển 3: DP.133 “Hết cấm vượt”',153),
(N'Biển 1.',0,N'',154),
(N'Biển 2.',1,N'Biển 2: DP135 “Hết mọi lệnh cấm”;',154),
(N'Cả ba biển.',0,N'',154),
(N'Biển 1.',1,N'Biển 1: I424a “Cầu vượt qua đường cho người đi bộ; Biển 2: I424c “Hầm chui qua đường cho người đi bộ” nên đáp án đúng là biển 1.',155),
(N'Biển 2.',0,N'',155),
(N'Cả hai biển.',0,N'',155),
(N'Biển 1.',0,N'',156),
(N'Biển 2.',1,N'Giải thích: Biển 1: I424b “Cầu vượt qua đường cho người đi bộ”; Biển 2: I424d “Hầm chui qua đường cho người đi bộ” nên đáp án đúng là biển 2.',156),
(N'Cả hai biển.',0,N'',156),
(N'Biển 1.',0,N'',157),
(N'Biển 2.',1,N'',157),
(N'Biển 3.',0,N'',157),
(N'Dừng xe tại khu vực có trạm Cảnh sát giao thông.',0,N'',158),
(N'Tiếp tục lưu thông với tốc độ bình thường.',0,N'',158),
(N'Phải giảm tốc độ đến mức an toàn và không được vượt khi đi qua khu vực này.',1,N'Giải thích: Biển I.436 “Trạm cảnh sát giảo thông”. 
Các phương tiện phải giảm tốc độ đến mức an toàn và không được vượt khi đi qua khu vực này.',158),
(N'Đi thẳng hoặc rẽ trái trên cầu vượt.',0,N'',159),
(N'Đi thẳng hoặc rẽ phải trên cầu vượt.',0,N'',159),
(N'Báo hiệu cầu vượt liên thông.',1,N'',159),
(N'Vạch 1.',0,N'',160),
(N'Vạch 2.',0,N'',160),
(N'Vạch 1 và 2.',1,N'',160),
(N'Vạch 1.',0,N'',161),
(N'Vạch 2.',1,N'',161),
(N'Vạch 3.',0,N'',161),
(N'Vạch 1.',0,N'',162),
(N'Vạch 2.',0,N'',162),
(N'Vạch 1 và 3.',1,N'',162),
(N'Phân chia hai chiều xe chạy ngược chiều nhau.',0,N'',163),
(N'Phân chia các làn xe chạy cùng chiều nhau.',0,N'',163),
(N'Vạch 1.',0,N'',164),
(N'Vạch 2.',0,N'',164),
(N'Vạch 1 và vạch 3.',1,N'',164),
(N'Vị trí dừng xe của các phương tiện vận tải hành khách công cộng.',1,N'Giải thích: Vạch 9.2: Vạch quy đình vị trí dừng đỗ của phương tiện giao thông công cộng trên đường.',165),
(N'Báo cho người điều khiển được dừng phương tiện trong phạm vi phần mặt đường có bố trí vạch để tránh ùn tắc giao thông.',0,N'',165),
(N'Dùng để xác định vị trí giữa các phương tiện trên đường.',0,N'',165),
(N'Xe tải, xe khách, xe con, mô tô.',0,N'',166),
(N'Xe tải, mô tô, xe khách, xe con.',1,N'Thứ tự ưu tiên: Xe ưu tiên- Đường ưu tiên- Đường cùng cấp theo thứ tự bên phải trống – rẽ phải – đi thẳng – rẽ trái.',166),
(N'Xe khách, xe tải, xe con, mô tô.',0,N'',166),
(N'Xe tải, xe con, mô tô.',0,N'',167),
(N'Xe con, xe tải, mô tô.',0,N'',167),
(N'Mô tô, xe con, xe tải.',1,N'Thứ tự ưu tiên: Xe ưu tiên- Đường ưu tiên- Đường cùng cấp theo thứ tự bên phải trống – rẽ phải – đi thẳng – rẽ trái.',167),
(N'Mô tô.',0,N'',168),
(N'Xe con.',1,N'Giải thích: Xe con được đi trước vì mô tô có biển STOP trước mặt.',168),
(N'Mô tô.',0,N'',169),
(N'Xe cứu thương.',1,N'Giải thích: Xe ưu tiên đi trước.',169),
(N'Xe con và xe khách.',1,N'Giải thích: Xe con và xe khách đang ở làn đường có tín hiệu đèn xanh nên được phép đi.',170),
(N'Mô tô.',0,N'',170),
(N'Xe khách, xe tải, mô tô.',1,N'Giải thích: 
1. Xe khách: Sai làn, đi thẳng đèn đang đỏ;
2. Xe tải: Sai làn: Đi trên làn đi thẳng trong khi thực hiện rẽ trái.
3. Xe mô tô: Sai làn: Đi trên làn rẽ trái trong khi thực hiện rẽ phải.
Nên đáp án đúng là xe khách, xe tải và xe mô tô đều vi phạm quy tắc giao thông.',171),
(N'Xe tải, xe con, mô tô.',0,N'',171),
(N'Xe khách, xe con, mô tô.',0,N'',171),
(N'Xe khách, xe tải, mô tô, xe con.',0,N'',172),
(N'Xe con, xe khách, xe tải, mô tô.',0,N'',172),
(N'Mô tô, xe tải, xe khách, xe con.',1,N'Giải thích: Giao nhau cùng cấp có vòng xuyến: Chưa vào vòng xuyến thì ưu tiên xe bên phải; đã vào vòng xuyến ưu tiên xe từ bên trái tới.
Toàn bộ các xe chưa vào vòng xuyến nên ưu tiên xe bên phải.
Thứ tự sẽ là mô tô, xe tải, xe khách, xe con.',172),
(N'Xe tải.',1,N'Giải thích: Biển cấm đỗ xe tải (ở biển phụ) nên chỉ có xe tải vi phạm.',173),
(N'Xe con và mô tô.',0,N'',173),
(N'Cả ba xe.',0,N'',173),
(N'Cả ba hướng.',1,N'Giải thích: 
Bạn lưu ý câu hỏi này về hướng đi của xe GẮN MÁY. Hướng 1 và 3 chắn chắn là đi được rồi. 
Với hướng 2, biển báo cấm mô tô đi vào chỉ có tác dụng với xe mô tô nên xe gắn máy không có hiệu lực. DO đó vẫn đi vào bình thường. ',174),
(N'Chỉ hướng 1 và 3.',0,N'',174),
(N'Chỉ hướng 1.',0,N'',174),
(N'Cả hai xe.',1,N'Giải thích: Biển cấm đỗ xe ở cả phía trước và phía sau biển (ở biển báo phụ) nên cả 2 xe vi phạm.',175),
(N'Không xe nào vi phạm.',0,N'',175),
(N'Chỉ xe mô tô vi phạm.',0,N'',175),
(N'Chỉ mô tô.',0,N'',176),
(N'Chỉ xe tải.',0,N'',176),
(N'Cả ba xe.',1,N'Giải thích: Xe tải đậu trái đường; Xe con và mô tô đậu xe đè vạch nên cả 3 xe vi phạm.',176),
(N'Đúng.',0,N'',177),
(N'Không đúng.',1,N'Giải thích: Xe tải kéo xe mô tô 3 bánh như trên hình là không đúng vì đi vào đường có biển P.108 “Cấm ô tô kéo moóc” kể cả xe máy, xe ô tô khách kéo theo rơ moóc đi qua.',177),
(N'Xe con.',0,N'',178),
(N'Xe mô tô.',1,N'Giải thích: 
Cả 2 xe đều gặp đèn xanh nên áp dụng quy tắc đường cùng cấp: Bên phải trống – Rẽ phải – Đi thẳng – Rẽ trái.
Nên đáp án đúng là xe mô tô rẽ phải được quyền đi trước. Xe con rẽ trái phải nhường đường.',178),
(N'Xe con (A), mô tô, xe con (B), xe đạp.',0,N'',179),
(N'Xe con (A), xe con (B), mô tô  + xe đạp.',0,N'',179),
(N'Mô tô + xe đạp, xe con (A), xe con (B).',1,N'Giải thích:
Thứ tự ưu tiên đường cùng cấp: Xe ưu tiên – Đường ưu tiên – Bên phải trống – Rẽ phải – Đi thẳng – Rẽ trái.',179),
(N'Mô tô.',1,N'Giải thích: Thứ tự ưu tiên: Xe ưu tiên – Đường ưu tiên – Bên phải trống – Rẽ trái – Đi thẳng – Rẽ trái. Xe mô tô rẽ trái từ đường ưu tiên vào đường ưu tiên (theo biển báo và biển phụ) nên được quyền đi trước.',180),
(N'Xe con.',0,N'',180),
(N'Xe khách.',0,N'',181),
(N'Mô tô.',0,N'',181),
(N'Xe con.',1,N'Giải thích: Xe con quay đầu đè vạch liền trên đường nên vi phạm.',181),
(N'Các xe ở phía tay phải và tay trái của người điều khiển được phép đi thẳng.',0,N'',182),
(N'Cho phép các xe ở mọi hướng được rẽ phải.',0,N'',182),
(N'Tất cả các xe phải dừng lại trước ngã tư, trừ những xe đã ở trong ngã tư được phép tiếp tục đi.',1,N'Giải thích: Giơ tay thẳng đứng: Tất cả dừng, trừ xe đã ở trong ngã tư được phép đi;
Giang tay ngang: Trái phải đi; Trước sau dừng; 
Tay phải giơ trước: sau, phải dừng, trước rẽ trái, trái đi các hướng, người đi bộ qua đường đi sau người điề',182),
(N'Mô tô, xe con.',0,N'',183),
(N'Xe con, xe tải.',0,N'',183),
(N'Mô tô, xe tải.',1,N'Giải thích: Giang ngang tay: Trái phải đi; Trước sau dừng. Xe mô tô và xe tải được phép đi là đáp án đúng.',183),
(N'Chỉ xe khách, mô tô.',0,N'',184),
(N'Tất cả các loại xe trên.',1,N'Giải thích: Xe khách chờ đèn đỏ rẽ trái. Xe tải đi thẳng và rẽ phải theo tín hiệu đèn xanh. Xe con đi thẳng và rẽ phải theo tín hiệu đèn xanh. Xe mô tô chờ đèn đỏ rẽ trái. Nên tất cả xe đều chấp hành.',184),
(N'Không xe nào chấp hành đúng quy tắc giao thông.',0,N'',184),
(N'Cả ba hướng.',0,N'',185),
(N'Hướng 1 và 2.',0,N'',185),
(N'Hướng 1 và 3.',1,N'Giải thích: Hướng 2 có biển số P.104 “Cấm mô tô”
Hướng 3 Biển số P.103a “Cấm ô tô” nhưng không cấm mô tô. Nên đáp án đúng là hướng 1 và hướng 3.',185),
(N'Xe công an, xe quân sự, xe con + mô tô.',0,N'',186),
(N'Xe quân sự, xe công an, xe con +mô tô.',1,N'',186),
(N'Xe mô tô + xe con, xe quân sự, xe công an.',0,N'',186),
(N'Xe con (E), mô tô (C).',1,N'Giải thích: Xe mô tô C chạy vào làn danh riêng xe ô tô: Vi phạm; Xe con E chạy vào làn danh riêng xe máy: Vi phạm.',187),
(N'Xe tải (A), mô tô (D).',0,N'',187),
(N'Xe khách (B), mô tô (C).',0,N'',187),
(N'Xe con (B), mô tô (C).',0,N'',188),
(N'Xe con (A), mô tô (C).',0,N'',188),
(N'Xe con (E), mô tô (D).',1,N'Giải thích: Nhìn vào bảng chỉ dẫn loại phương tiện theo làn đường: Xe con (E) đi trên làn danh riêng cho mô tô nên vi phạm: Xe mô tô (D) chạy trên làn dành riêng cho ô tô nên cũng vi phạm.',188),
(N'Cho phép.',0,N'',189),
(N'Không được vượt.',1,N'',189),
(N'Xe mô tô.',0,N'',190),
(N'Xe ô tô con.',0,N'',190),
(N'Cả hai xe.',1,N'Giải thích: Biển số R.301a chỉ cho phép các phương tiện đi thẳng trong khi cả 2 xe đều có tín hiệu xe nhan rẽ sang hướng khách nên cả 2 xe đều vi phạm quy tắc giao thông.',190),
(N'Xe con.',0,N'',191),
(N'Xe tải.',1,N'Giải thích: Xe con trong cả 2 phía đều đang đúng làn đường và đi theo hướng mà đèn xanh đang bật nên đúng quy tắc giao thông.
Xe tải trong cả 2 phía đều ở sai làn đường so với hướng rẽ nên vi phạm quy tắc giao thông.',191),
(N'Xe con, xe tải.',0,N'',191),
(N'Xe tải, xe con.',0,N'',192),
(N'Xe khách, xe con.',0,N'',192),
(N'Xe khách, xe tải.',1,N'Giải thích: Xe con và xe mô tô đang ở đúng làn đường, đúng hướng rẽ với tín hiệu đèn xanh nên đúng quy tắc giao thông.',192),
(N'Xe con, xe khách, xe tải.',0,N'',193),
(N'Xe tải, xe khách, xe mô tô.',1,N'Giải thích: 
Xe con đi đúng làn đường theo hướng rẽ và tín hiệu đèn.
Xe khách: Sai làn đường và tín hiệu đèn.
Xe tải: Đi thẳng vi phạm đèn đỏ.
Xe mô tô: Đi thẳng vi phạm đèn đỏ.',193),
(N'Cả bốn xe.',0,N'',193),
(N'Xe tải, mô tô.',0,N'',194),
(N'Xe khách, mô tô.',1,N'Giải thích: Xe con và xe tải: Vi phạm tín hiệu đèn;
Xe khách và xe mô tô: Đúng làn đường và đúng tín hiệu đèn.',194),
(N'Mô tô, xe con.',0,N'',194),
(N'Xe của bạn, mô tô, xe con.',0,N'',195),
(N'Xe con, xe của bạn, mô tô.',0,N'',195),
(N'Mô tô, xe con, xe của bạn.',1,N'Giải thích: Thứ tự ưu tiên: Xe ưu tiên – Đường ưu tiên – Đường cùng cấp: Bên phải trống, rẽ phải, đi thẳng, rẽ trái.
Biển báo phía trước là đường ưu tiên và biển phụ báo hướng di chuyển của xe mô tô là hướng ưu tiên.
1. Xe mô tô: Đường ưu tiên;
2. Xe con: Đường không ưu tiên, bên phải trống;
3.  Xe của bạn: Đường không ưu tiên, bên phải vướng xe con.',195),
(N'Xe của bạn, mô tô, xe con.',0,N'',196),
(N'Xe con, xe của bạn, mô tô.',1,N'Giải thích: Thứ tự ưu tiên: Xe ưu tiên – Đường ưu tiên – Đường cùng cấp: Bên phải trống, rẽ phải, đi thẳng, rẽ trái.
1. Xe con: Rẽ phải; 2: Xe của bạn: Đi thẳng; 3. Mô tô: Rẽ trái.',196),
(N'Mô tô, xe con, xe của bạn.',0,N'',196),
(N'Giảm tốc độ, rẽ phải sau xe tải và xe đạp.',1,N'Giải thích: Xe tải đã vào nơi giao nhau trước nên sẽ được ưu tiên trước. Biển báo phía trước là đường ưu tiên dành cho xe thô sơ nên phải nhường đường cho xe đạp. Do đó, xe bạn rẽ phải sau xe tải và xe đạp.',197),
(N'Tăng tốc độ, rẽ phải trước xe tải và xe đạp.',0,N'',197),
(N'Tăng tốc độ, rẽ phải trước xe đạp.',0,N'',197),
(N'Xe con.',1,N'Giải thích:Biển số W.211a “Giao nhau với đường sắt không có rào chắn” thì các phương tiện đứng cách xa đường sắt tối thiểu 5m nên xe con đúng.',198),
(N'Xe mô tô.',0,N'',198),
(N'Cả hai xe đều đúng.',0,N'',198),
(N'Quan sát nếu thấy không có tàu thì tăng tốc cho xe vượt qua đường sắt.',0,N'',199),
(N'Dừng lại trước rào chắn một khoảng cách an toàn.',1,N'Giải thích: Bắt buộc phải dừng xe.',199),
(N'Ra tín hiệu, yêu cầu người gác chắn tàu kéo chậm Barie để xe bạn qua.',0,N'',199),
(N'Vượt về phía bên phải để đi tiếp.',0,N'',200),
(N'Giảm tốc độ chờ xe container rẽ xong rồi tiếp tục đi.',1,N'iải thích: Giảm tốc độc chờ xe đầu kéo rẽ phải rồi mới tiếp tục đi.',200),
(N'Vượt về phía bên trái để đi tiếp.',0,N'',200)

select * from USERS
select * from LOAICAUHOI
select * from CAUHOI
select * from LOAIDE
select * from DETHI
select * from CAUHOI_DETHI
select * from DAPAN