/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testView;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import testConnectSQL.ConnectSQL;
import testController.changePasswordController;

/**
 *
 * @author PC
 */
public class Dgdoimatkhau extends javax.swing.JDialog {

    /**
     * Creates new form Dgdoimatkhau
     */
    public ConnectSQL con = new ConnectSQL();
    public changePasswordController change = new changePasswordController();

    public Dgdoimatkhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(580, 520);
        setLocationRelativeTo(null);
        txtemail.setText(Run.user.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitler = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btndoimk = new javax.swing.JButton();
        pwmkcu = new javax.swing.JPasswordField();
        pwmkmoi = new javax.swing.JPasswordField();
        pwcomfimpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(575, 520));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lbltitler.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltitler.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(lbltitler);
        lbltitler.setBounds(207, 0, 186, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Email");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 170, 40);

        txtemail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtemail.setEnabled(false);
        jPanel1.add(txtemail);
        txtemail.setBounds(190, 100, 340, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mật Khẩu Cũ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 170, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mật Khẩu Mới");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 240, 170, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nhập Lại Mật Khẩu Mới");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 310, 170, 40);

        btndoimk.setBackground(new java.awt.Color(78, 180, 84));
        btndoimk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndoimk.setForeground(new java.awt.Color(255, 255, 255));
        btndoimk.setText("ĐỔI MẬT KHẨU");
        btndoimk.setBorderPainted(false);
        btndoimk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btndoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoimkActionPerformed(evt);
            }
        });
        jPanel1.add(btndoimk);
        btndoimk.setBounds(120, 390, 335, 35);
        jPanel1.add(pwmkcu);
        pwmkcu.setBounds(190, 170, 340, 40);
        jPanel1.add(pwmkmoi);
        pwmkmoi.setBounds(190, 240, 340, 40);
        jPanel1.add(pwcomfimpass);
        pwcomfimpass.setBounds(190, 310, 340, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoimkActionPerformed
        chanepass();
    }//GEN-LAST:event_btndoimkActionPerformed
    public boolean check() {
        String pb = null;
        String pa = pwmkmoi.getText();
        try {
            // "^$" bắt đầu và kết thúc
            //.* = bất kỳ ký tự nào và xuất hiện ít nhất 0 lần
            // .*[a-z] trước a-z có thể có hoặc không có ký tự nào
            //?=.*[a-z] chuỗi phải bắt đầu bằng a-z hoặc ký tự bất kỳ theo sau bởi a-z vd: abc || 2abc
            String patern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,}$";
            if (pwmkcu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "vui lòng nhập mật khẩu cũ của bạn");
                pwmkcu.requestFocus();
                return false;
            }
            if (pwmkmoi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "vui lòng nhập mật khẩu mới");
                pwmkmoi.requestFocus();
                return false;
            }
            if (pwcomfimpass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "vui lòng nhập lại mật khẩu mới");
                pwcomfimpass.requestFocus();
                return false;
            }
            if(pwmkmoi.getText().equalsIgnoreCase(pwmkcu.getText())){
                JOptionPane.showMessageDialog(this, "mật khẩu mới không được giống mk cũ");
            }
            if (!pwmkmoi.getText().trim().matches(patern)) {
                JOptionPane.showMessageDialog(this, "mật khẩu phải chứa chữ hoa, chữ thường và số");
                return false;
            }
            if (!pa.equalsIgnoreCase(pwcomfimpass.getText().trim())) {
                JOptionPane.showMessageDialog(this, "vui lòng nhập lại đúng mật khẩu mới");
                return false;
            }
            try {

                String sql = "select PASS from USERS where EMAIL = ? ";
                ResultSet rs = con.prepareExcuteQuery(sql, txtemail.getText());
                while (rs.next()) {
                    pb = rs.getString("PASS");
                }
                if (!pwmkcu.getText().equalsIgnoreCase(pb)) {
                    JOptionPane.showMessageDialog(this, "mật khẩu cũ của bạn không đúng");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "lỗi check mk" + e);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi check " + e);
        }

        return true;
    }

    public void chanepass() {
        try {
            if (check() == false) {
                return;
            } else {
                String pass = pwmkmoi.getText();
                String email = txtemail.getText();
                change.changePassword(pass, email);
                JOptionPane.showMessageDialog(this, "đổi mật khẩu thành công");
                this.dispose();
                setVisible(false);
                Run.home.setVisible(false);
                Run.frLogin();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi" + e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dgdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dgdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dgdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dgdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dgdoimatkhau dialog = new Dgdoimatkhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoimk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltitler;
    private javax.swing.JPasswordField pwcomfimpass;
    private javax.swing.JPasswordField pwmkcu;
    private javax.swing.JPasswordField pwmkmoi;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
