package testView;

/**
 *
 * @author hai95
 */
public class dgAddQuestion extends java.awt.Dialog {

    /**
     * Creates new form dgAddQuestion
     */
    public dgAddQuestion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(710, 730);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDapAn3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDapAn1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDapAn2 = new javax.swing.JTextArea();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel1.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thêm câu hỏi");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(120, 30, 420, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Đáp án 3");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 530, 70, 20);

        txtNoiDung.setColumns(20);
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 660, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nội dung");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 90, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Đáp án 1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 290, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Đáp án 2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 410, 70, 20);

        txtDapAn3.setColumns(20);
        txtDapAn3.setRows(5);
        jScrollPane2.setViewportView(txtDapAn3);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 560, 650, 76);

        txtDapAn1.setColumns(20);
        txtDapAn1.setRows(5);
        jScrollPane3.setViewportView(txtDapAn1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(30, 320, 650, 76);

        txtDapAn2.setColumns(20);
        txtDapAn2.setRows(5);
        jScrollPane4.setViewportView(txtDapAn2);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(30, 440, 650, 76);

        btnXacNhan.setText("Xác nhận");
        jPanel1.add(btnXacNhan);
        btnXacNhan.setBounds(133, 670, 90, 23);

        btnHuy.setText("Hủy");
        jPanel1.add(btnHuy);
        btnHuy.setBounds(410, 670, 90, 23);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgAddQuestion dialog = new dgAddQuestion(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtDapAn1;
    private javax.swing.JTextArea txtDapAn2;
    private javax.swing.JTextArea txtDapAn3;
    private javax.swing.JTextArea txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
