package testView;
import java.security.interfaces.RSAKey;
import testConnectSQL.ConnectSQL;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import testConnectSQL.*;
import testController.QuestionController;
import testModel.*;
/**
 *
 * @author Mint
 */
public class dgCauHoiLiet extends javax.swing.JFrame {

    /**
     * Creates new form dgCauHoiLiet
     */
    Connection con;
    
    int index = 0;
    static QuestionController quesController = new QuestionController();

    public dgCauHoiLiet() {
        initComponents();
        setTitle("19 câu hỏi liệt");
        setLocationRelativeTo(null);
        loadData(); 
        lblCauHoi.setText("Câu hỏi " + index);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadData(){
        try {
            List<Question> listQuestions = quesController.getListQuestion();
            List<Answer> listAnswers = quesController.getListAnswers();
            
            List<Question> listCauLietQuestions = quesController.getCauLiet(listQuestions);      
            //load câu hỏi
            txpCauHoi.setText(listCauLietQuestions.get(index).getNoiDung());
            System.out.println(listCauLietQuestions.size());
            //load đáp án
            Question ques = listCauLietQuestions.get(index);
            List<Answer> listCauLietAnswer = quesController.getAnswerCauLiet(ques.getId(), listAnswers);
            txpA.setText("");
            txpB.setText("");
            txpC.setText("");
            txpA.setText(listCauLietAnswer.get(0).getNoiDung());
            txpB.setText(listCauLietAnswer.get(1).getNoiDung());
            txpC.setText(listCauLietAnswer.get(2).getNoiDung());
            
           
        } catch (Exception e) {
        }
    }
    public void showQuestion(){
        
    }
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCauHoi = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        rdoC = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpC = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txpCauHoi = new javax.swing.JTextPane();
        rdoA = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txpA = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txpB = new javax.swing.JTextPane();
        rdoB = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txpD = new javax.swing.JTextPane();
        rdoD = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        pnlMenuCauHoi = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnPrev1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(238, 246, 237));
        jPanel3.setLayout(null);

        lblCauHoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCauHoi.setForeground(new java.awt.Color(58, 180, 84));
        lblCauHoi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCauHoiAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(lblCauHoi);
        lblCauHoi.setBounds(20, 10, 250, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 50);
        jPanel2.add(lblHinh);
        lblHinh.setBounds(530, 200, 450, 250);

        rdoC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoC);
        jPanel2.add(rdoC);
        rdoC.setBounds(20, 350, 20, 21);

        txpC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpC.setEnabled(false);
        txpC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txpCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txpC);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 340, 460, 50);

        txpCauHoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txpCauHoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txpCauHoi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpCauHoi.setEnabled(false);
        jScrollPane3.setViewportView(txpCauHoi);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 970, 100);

        rdoA.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoA);
        jPanel2.add(rdoA);
        rdoA.setBounds(20, 210, 20, 21);

        txpA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpA.setEnabled(false);
        txpA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txpAMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(txpA);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(50, 200, 460, 50);

        txpB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpB.setEnabled(false);
        txpB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txpBMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(txpB);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(50, 270, 460, 50);

        rdoB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoB);
        jPanel2.add(rdoB);
        rdoB.setBounds(20, 280, 20, 21);

        txpD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpD.setEnabled(false);
        txpD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txpDMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(txpD);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(50, 410, 460, 50);

        rdoD.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoD);
        jPanel2.add(rdoD);
        rdoD.setBounds(20, 420, 20, 21);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 90, 1000, 510);

        jPanel4.setBackground(new java.awt.Color(78, 180, 84));
        jPanel4.setLayout(null);

        btnMenu1.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(78, 180, 84));
        btnMenu1.setText("Menu");
        btnMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 227, 145)));
        btnMenu1.setBorderPainted(false);
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnMenu1);
        btnMenu1.setBounds(20, 10, 80, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1200, 50);

        pnlMenuCauHoi.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.add(pnlMenuCauHoi);
        pnlMenuCauHoi.setBounds(100, 690, 1000, 70);

        btnNext.setText("Câu tiếp theo");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(280, 650, 150, 40);

        btnPrev1.setText("Câu trước");
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrev1);
        btnPrev1.setBounds(110, 651, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
      index++;
      loadData();
      lblCauHoi.setText("Câu hỏi " + index);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
       index--;
       loadData();
       lblCauHoi.setText("Câu hỏi " + index);
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void lblCauHoiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCauHoiAncestorAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lblCauHoiAncestorAdded

    private void txpAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpAMouseClicked
        // TODO add your handling code here:
        rdoA.setSelected(true);
    }//GEN-LAST:event_txpAMouseClicked

    private void txpBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpBMouseClicked
        // TODO add your handling code here:
        rdoB.setSelected(true);
    }//GEN-LAST:event_txpBMouseClicked

    private void txpCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpCMouseClicked
        // TODO add your handling code here:
        rdoC.setSelected(true);
    }//GEN-LAST:event_txpCMouseClicked

    private void txpDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpDMouseClicked
        // TODO add your handling code here:
        rdoD.setSelected(true);
    }//GEN-LAST:event_txpDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiLiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiLiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiLiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiLiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dgCauHoiLiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JPanel pnlMenuCauHoi;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoC;
    private javax.swing.JRadioButton rdoD;
    private javax.swing.JTextPane txpA;
    private javax.swing.JTextPane txpB;
    private javax.swing.JTextPane txpC;
    private javax.swing.JTextPane txpCauHoi;
    private javax.swing.JTextPane txpD;
    // End of variables declaration//GEN-END:variables
}
