package testView;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hai95
 */
public class dgExam extends java.awt.Dialog {

    /**
     * Creates new form dgQuestion
     */
    public dgExam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(1200, 800);
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/cau166.png"));
        lblHinh.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblMaDe = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCauHoi = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        rdoC = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpC = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txpCauHoi = new javax.swing.JTextPane();
        rdoA = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txpA = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txpB = new javax.swing.JTextPane();
        rdoB = new javax.swing.JRadioButton();
        btn25 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();

        setTitle("Question");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setLayout(null);

        lblMaDe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMaDe.setText("Đề thi số 1");
        jPanel1.add(lblMaDe);
        lblMaDe.setBounds(50, 30, 440, 30);

        jToolBar1.setBackground(new java.awt.Color(78, 180, 84));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(78, 180, 84));
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jSeparator1.setSeparatorSize(new java.awt.Dimension(10, 40));
        jToolBar1.add(jSeparator1);

        jButton2.setBackground(new java.awt.Color(78, 180, 84));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Menu");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(80, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 40));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 60, 1200, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(238, 246, 237));
        jPanel3.setLayout(null);

        lblCauHoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCauHoi.setForeground(new java.awt.Color(58, 180, 84));
        lblCauHoi.setText("Câu hỏi 8");
        jPanel3.add(lblCauHoi);
        lblCauHoi.setBounds(20, 10, 250, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 50);
        jPanel2.add(lblHinh);
        lblHinh.setBounds(530, 200, 450, 250);

        rdoC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoC);
        jPanel2.add(rdoC);
        rdoC.setBounds(20, 350, 20, 21);

        txpC.setBackground(new java.awt.Color(255, 255, 255));
        txpC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpC.setEnabled(false);
        jScrollPane2.setViewportView(txpC);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 340, 460, 50);

        txpCauHoi.setBackground(new java.awt.Color(255, 255, 255));
        txpCauHoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txpCauHoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txpCauHoi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpCauHoi.setEnabled(false);
        jScrollPane3.setViewportView(txpCauHoi);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 970, 100);

        rdoA.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoA);
        jPanel2.add(rdoA);
        rdoA.setBounds(20, 210, 20, 21);

        txpA.setBackground(new java.awt.Color(255, 255, 255));
        txpA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpA.setEnabled(false);
        jScrollPane4.setViewportView(txpA);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(50, 200, 460, 50);

        txpB.setBackground(new java.awt.Color(255, 255, 255));
        txpB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpB.setEnabled(false);
        jScrollPane5.setViewportView(txpB);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(50, 270, 460, 50);

        rdoB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoB);
        jPanel2.add(rdoB);
        rdoB.setBounds(20, 280, 20, 21);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 130, 1000, 580);

        btn25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn25.setText("25");
        btn25.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn25);
        btn25.setBounds(1060, 740, 30, 23);

        btn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1.setText("1");
        btn1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn1);
        btn1.setBounds(100, 740, 30, 23);

        btn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn2.setText("2");
        btn2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn2);
        btn2.setBounds(140, 740, 30, 23);

        btn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn3.setText("3");
        btn3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn3);
        btn3.setBounds(180, 740, 30, 23);

        btn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn4.setText("4");
        btn4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn4);
        btn4.setBounds(220, 740, 30, 23);

        btn5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn5.setText("5");
        btn5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn5);
        btn5.setBounds(260, 740, 30, 23);

        btn6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn6.setText("6");
        btn6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn6);
        btn6.setBounds(300, 740, 30, 23);

        btn7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn7.setText("7");
        btn7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn7);
        btn7.setBounds(340, 740, 30, 23);

        btn8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn8.setText("8");
        btn8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn8);
        btn8.setBounds(380, 740, 30, 23);

        btn9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn9.setText("9");
        btn9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn9);
        btn9.setBounds(420, 740, 30, 23);

        btn10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn10.setText("10");
        btn10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn10);
        btn10.setBounds(460, 740, 30, 23);

        btn11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn11.setText("11");
        btn11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn11);
        btn11.setBounds(500, 740, 30, 23);

        btn12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn12.setText("12");
        btn12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn12);
        btn12.setBounds(540, 740, 30, 23);

        btn13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn13.setText("13");
        btn13.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn13);
        btn13.setBounds(580, 740, 30, 23);

        btn14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn14.setText("14");
        btn14.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn14);
        btn14.setBounds(620, 740, 30, 23);

        btn15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn15.setText("15");
        btn15.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn15);
        btn15.setBounds(660, 740, 30, 23);

        btn16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn16.setText("16");
        btn16.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn16);
        btn16.setBounds(700, 740, 30, 23);

        btn17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn17.setText("17");
        btn17.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn17);
        btn17.setBounds(740, 740, 30, 23);

        btn18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn18.setText("18");
        btn18.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn18);
        btn18.setBounds(780, 740, 30, 23);

        btn19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn19.setText("19");
        btn19.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn19);
        btn19.setBounds(820, 740, 30, 23);

        btn20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn20.setText("20");
        btn20.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn20);
        btn20.setBounds(860, 740, 30, 23);

        btn21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn21.setText("21");
        btn21.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn21);
        btn21.setBounds(900, 740, 30, 23);

        btn22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn22.setText("22");
        btn22.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn22);
        btn22.setBounds(940, 740, 30, 23);

        btn23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn23.setText("23");
        btn23.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn23);
        btn23.setBounds(980, 740, 30, 23);

        btn24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn24.setText("24");
        btn24.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btn24);
        btn24.setBounds(1020, 740, 30, 23);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgExam dialog = new dgExam(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMaDe;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoC;
    private javax.swing.JTextPane txpA;
    private javax.swing.JTextPane txpB;
    private javax.swing.JTextPane txpC;
    private javax.swing.JTextPane txpCauHoi;
    // End of variables declaration//GEN-END:variables
}
