package testView;

import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author hai95
 */
public class dgExam extends java.awt.Dialog {

    /**
     * Creates new form dgQuestion
     */
    public dgExam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(1200, 800);
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/cau166.png"));
        lblHinh.setIcon(icon);
        timeExam();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblMaDe = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCauHoi = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        rdoC = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpC = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txpCauHoi = new javax.swing.JTextPane();
        rdoA = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txpA = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txpB = new javax.swing.JTextPane();
        rdoB = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenuCauHoi = new javax.swing.JPanel();

        setTitle("Question");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setLayout(null);

        lblMaDe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMaDe.setText("Đề thi số 1");
        jPanel1.add(lblMaDe);
        lblMaDe.setBounds(30, 20, 210, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(238, 246, 237));
        jPanel3.setLayout(null);

        lblCauHoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblCauHoi.setForeground(new java.awt.Color(58, 180, 84));
        lblCauHoi.setText("Câu hỏi 8");
        jPanel3.add(lblCauHoi);
        lblCauHoi.setBounds(20, 10, 250, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 50);
        jPanel2.add(lblHinh);
        lblHinh.setBounds(530, 200, 450, 250);

        rdoC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoC);
        jPanel2.add(rdoC);
        rdoC.setBounds(20, 350, 20, 21);

        txpC.setBackground(new java.awt.Color(255, 255, 255));
        txpC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpC.setEnabled(false);
        jScrollPane2.setViewportView(txpC);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 340, 460, 50);

        txpCauHoi.setBackground(new java.awt.Color(255, 255, 255));
        txpCauHoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txpCauHoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txpCauHoi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpCauHoi.setEnabled(false);
        jScrollPane3.setViewportView(txpCauHoi);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 970, 100);

        rdoA.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoA);
        jPanel2.add(rdoA);
        rdoA.setBounds(20, 210, 20, 21);

        txpA.setBackground(new java.awt.Color(255, 255, 255));
        txpA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpA.setEnabled(false);
        jScrollPane4.setViewportView(txpA);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(50, 200, 460, 50);

        txpB.setBackground(new java.awt.Color(255, 255, 255));
        txpB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txpB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txpB.setEnabled(false);
        jScrollPane5.setViewportView(txpB);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(50, 270, 460, 50);

        rdoB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoB);
        jPanel2.add(rdoB);
        rdoB.setBounds(20, 280, 20, 21);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 170, 1000, 510);

        jPanel4.setBackground(new java.awt.Color(78, 180, 84));
        jPanel4.setLayout(null);

        btnMenu.setBackground(new java.awt.Color(255, 118, 89));
        btnMenu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Kết thúc");
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 118, 89)));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel4.add(btnMenu);
        btnMenu.setBounds(1070, 10, 100, 30);

        btnMenu1.setBackground(new java.awt.Color(78, 227, 145));
        btnMenu1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu1.setText("Menu");
        btnMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 227, 145)));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnMenu1);
        btnMenu1.setBounds(20, 10, 80, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 60, 1200, 50);

        lblTimer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 51, 51));
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("12:35");
        jPanel1.add(lblTimer);
        lblTimer.setBounds(610, 120, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Thời gian còn lại:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 120, 130, 30);

        pnlMenuCauHoi.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.add(pnlMenuCauHoi);
        pnlMenuCauHoi.setBounds(100, 690, 1000, 70);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed
    public void timeExam() {
        Thread timeEx = new Thread() {
            int time = 900;

            @Override
            public void run() {
                while (true) {
                    time--;
                    if (time == 0) {
                        
                    }
                    int ss = time % 60;
                    int m = time / 60;
                    lblTimer.setText(m + " : " + ss);
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

            }
        };
        timeEx.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgExam dialog = new dgExam(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMaDe;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JPanel pnlMenuCauHoi;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoC;
    private javax.swing.JTextPane txpA;
    private javax.swing.JTextPane txpB;
    private javax.swing.JTextPane txpC;
    private javax.swing.JTextPane txpCauHoi;
    // End of variables declaration//GEN-END:variables
}
