package testView;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import testController.QuestionController;
import testModel.CauHoi_DeThi;
import testModel.Dethi;

/**
 *
 * @author hai95
 */
public class dgMenuDT extends java.awt.Dialog {

    QuestionController questionController = new QuestionController();
    List<Dethi> lstDeThi = new ArrayList<>();

    /**
     * Creates new form dgMenuDT
     */
    public dgMenuDT(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(1200, 800);
        jPanel1.setSize(1200, 800);
        setLocationRelativeTo(null);
        loadDT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnNewExam = new javax.swing.JButton();
        pnlDeThi = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(78, 180, 84));
        jPanel4.setLayout(null);

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(78, 180, 84));
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 227, 145)));
        btnHome.setBorderPainted(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel4.add(btnHome);
        btnHome.setBounds(20, 10, 80, 30);

        btnNewExam.setBackground(new java.awt.Color(255, 118, 89));
        btnNewExam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewExam.setForeground(new java.awt.Color(255, 255, 255));
        btnNewExam.setText("Đề mới");
        btnNewExam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 118, 89)));
        btnNewExam.setBorderPainted(false);
        btnNewExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewExamActionPerformed(evt);
            }
        });
        jPanel4.add(btnNewExam);
        btnNewExam.setBounds(1070, 10, 100, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 30, 1200, 50);

        pnlDeThi.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pnlDeThi);
        pnlDeThi.setBounds(100, 170, 1000, 510);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        Run.home.setVisible(true);
    }//GEN-LAST:event_closeDialog

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        Run.home.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnNewExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewExamActionPerformed
        // TODO add your handling code here:
        createExam();
    }//GEN-LAST:event_btnNewExamActionPerformed

    public void loadDT() {
        try {
            lstDeThi = questionController.getListDTbyEmail();
            pnlDeThi.removeAll();
            JButton[] btnDeThi = new JButton[lstDeThi.size()];
            for (int i = 0; i < lstDeThi.size(); i++) {
                btnDeThi[i] = new JButton();
                btnDeThi[i].setName(i + "");
                btnDeThi[i].setText("Đề thi " + (i + 1));
                btnDeThi[i].setSize(90, 90);
                btnDeThi[i].setFont(new java.awt.Font("Tahoma", 0, 16));
                if (lstDeThi.get(i).getTrangThai().equalsIgnoreCase("donot")) {
                    btnDeThi[i].setBackground(Color.GREEN);
                    btnDeThi[i].setForeground(Color.black);
                } else if (lstDeThi.get(i).getTrangThai().equalsIgnoreCase("doing")) {
                    btnDeThi[i].setBackground(Color.YELLOW);
                    btnDeThi[i].setForeground(Color.black);
                } else if (lstDeThi.get(i).getTrangThai().equalsIgnoreCase("pass")) {
                    btnDeThi[i].setBackground(Color.BLUE);
                    btnDeThi[i].setForeground(Color.white);
                } else if (lstDeThi.get(i).getTrangThai().equalsIgnoreCase("failed")) {
                    btnDeThi[i].setBackground(Color.red);
                    btnDeThi[i].setForeground(Color.white);
                }
                btnDeThi[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        int index = Integer.parseInt(e.getComponent().getName());
                        dgExam Exam = new dgExam(Run.home, true, lstDeThi.get(index));
                        Exam.setVisible(true);
                    }

                });
                pnlDeThi.add(btnDeThi[i]);
                pnlDeThi.updateUI();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed get Exam by email: " + e);
        }
    }

    public void createExam() {
        try {
            questionController.createExam();
            JOptionPane.showMessageDialog(this, "Create Exam success");
            loadDT();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed 10: Create Question Exam failed" + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgMenuDT dialog = new dgMenuDT(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNewExam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlDeThi;
    // End of variables declaration//GEN-END:variables
}
