package testView;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author hai95
 */
public class dgStudy extends java.awt.Dialog {

    /**
     * Creates new form Study
     */
    public dgStudy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(1200, 800);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl8 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl6 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setTitle("Học lý thuyết");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 248, 251));
        jPanel1.setLayout(null);

        btnMenu.setBackground(new java.awt.Color(78, 180, 84));
        btnMenu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menu");
        btnMenu.setBorderPainted(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu);
        btnMenu.setBounds(30, 60, 120, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        lbl8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl8.setText("Gồm 106 câu hỏi");
        jPanel4.add(lbl8);
        lbl8.setBounds(30, 70, 120, 20);

        lbl7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl7.setText("CÂU SA HÌNH");
        jPanel4.add(lbl7);
        lbl7.setBounds(30, 20, 260, 30);

        lbl9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl9.setForeground(new java.awt.Color(80, 199, 135));
        lbl9.setText("Đã làm 0/106");
        jPanel4.add(lbl9);
        lbl9.setBounds(30, 110, 120, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 460, 1140, 150);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(null);

        lbl6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl6.setForeground(new java.awt.Color(80, 199, 135));
        lbl6.setText("Đã làm 0/75");
        jPanel3.add(lbl6);
        lbl6.setBounds(30, 110, 120, 20);

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl5.setText("Gồm 75 câu hỏi");
        lbl5.setToolTipText("");
        jPanel3.add(lbl5);
        lbl5.setBounds(30, 70, 120, 20);

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl4.setText("CÂU HỎI KHÁI NIỆM VÀ QUY TẮC");
        jPanel3.add(lbl4);
        lbl4.setBounds(30, 20, 350, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 290, 1140, 150);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(null);

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl1.setText("CÂU HỎI LIỆT");
        jPanel2.add(lbl1);
        lbl1.setBounds(30, 20, 260, 30);

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl3.setForeground(new java.awt.Color(80, 199, 135));
        lbl3.setText("Đã làm 0/19");
        jPanel2.add(lbl3);
        lbl3.setBounds(30, 110, 120, 20);

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl2.setText("Gồm 19 câu hỏi");
        jPanel2.add(lbl2);
        lbl2.setBounds(30, 70, 120, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 120, 1140, 150);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    public void setColor(JPanel p, JLabel lb1, JLabel lb2, JLabel lb3){
        p.setBackground(new Color(78,180,84));
        lb1.setForeground(Color.WHITE);
        lb2.setForeground(Color.WHITE);
        lb3.setForeground(new Color(255,199,67));
    }
    public void resetColor(JPanel p1, JLabel lb1, JLabel lb2, JLabel lb3){
        p1.setBackground(Color.WHITE);
        lb1.setForeground(new Color(0,0,0));
        lb2.setForeground(new Color(0,0,0));
        lb3.setForeground(new Color(80,199,135));
        
    }
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // mở form câu hỏi liệt và đóng form study
        dispose();
        dgCauHoiLiet cauHoiLiet = new dgCauHoiLiet();
        cauHoiLiet.setVisible(true);    
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // mở form câu hỏi khái niệm & quy tắc và đóng form study
        dispose();
        dgCauHoiKhaiNiemVaQuyTac khaiNiemVaQuyTac = new dgCauHoiKhaiNiemVaQuyTac();
        khaiNiemVaQuyTac.setVisible(true); 
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        dispose();
        dgCauHoiSaHinh cauHoiSaHinh = new dgCauHoiSaHinh();
        cauHoiSaHinh.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        setColor(jPanel2,lbl1,lbl2,lbl3);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        resetColor(jPanel2,lbl1,lbl2,lbl3);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        setColor(jPanel3,lbl4,lbl5,lbl6);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        resetColor(jPanel3,lbl4,lbl5,lbl6);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4,lbl7,lbl8,lbl9);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        resetColor(jPanel4,lbl7,lbl8,lbl9);
    }//GEN-LAST:event_jPanel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiSaHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiSaHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiSaHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dgCauHoiSaHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dgStudy dialog = new dgStudy(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables
}
