package testView;

import javax.swing.JRootPane;

/**
 *
 * @author hai95
 * thêm icon vào 
 */

public class frHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public frHome() {
        initComponents();
        setsize();
    }
    public void setsize(){
        pnlHome.setSize(1200, 800);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        btnCauHoi = new javax.swing.JButton();
        btnLyThuyet = new javax.swing.JButton();
        btnThi = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ôn thi bằng lái xe máy");
        setAlwaysOnTop(true);

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));
        pnlHome.setPreferredSize(new java.awt.Dimension(1200, 800));
        pnlHome.setLayout(null);

        btnCauHoi.setBackground(new java.awt.Color(255, 118, 89));
        btnCauHoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnCauHoi.setIcon(new javax.swing.ImageIcon("E:\\5.Fork\\On-thi-bang-lai-xe\\LicenseTest\\src\\Images\\Question_fill.png")); // NOI18N
        btnCauHoi.setText("Bộ câu hỏi");
        btnCauHoi.setBorderPainted(false);
        btnCauHoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCauHoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauHoiActionPerformed(evt);
            }
        });
        pnlHome.add(btnCauHoi);
        btnCauHoi.setBounds(780, 220, 230, 180);

        btnLyThuyet.setBackground(new java.awt.Color(0, 182, 222));
        btnLyThuyet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLyThuyet.setForeground(new java.awt.Color(255, 255, 255));
        btnLyThuyet.setIcon(new javax.swing.ImageIcon("E:\\5.Fork\\On-thi-bang-lai-xe\\LicenseTest\\src\\Images\\Desk_alt_fill.png")); // NOI18N
        btnLyThuyet.setText("Học lý thuyết");
        btnLyThuyet.setBorderPainted(false);
        btnLyThuyet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLyThuyet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLyThuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLyThuyetActionPerformed(evt);
            }
        });
        pnlHome.add(btnLyThuyet);
        btnLyThuyet.setBounds(170, 220, 230, 180);

        btnThi.setBackground(new java.awt.Color(86, 222, 167));
        btnThi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThi.setForeground(new java.awt.Color(255, 255, 255));
        btnThi.setIcon(new javax.swing.ImageIcon("E:\\5.Fork\\On-thi-bang-lai-xe\\LicenseTest\\src\\Images\\File_dock_fill.png")); // NOI18N
        btnThi.setText("Thi thử");
        btnThi.setBorderPainted(false);
        btnThi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThiActionPerformed(evt);
            }
        });
        pnlHome.add(btnThi);
        btnThi.setBounds(400, 220, 380, 180);

        btnThongKe.setBackground(new java.awt.Color(158, 122, 194));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon("E:\\5.Fork\\On-thi-bang-lai-xe\\LicenseTest\\src\\Images\\Chart_alt_fill.png")); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setBorderPainted(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        pnlHome.add(btnThongKe);
        btnThongKe.setBounds(590, 400, 420, 170);

        btnTaiKhoan.setBackground(new java.awt.Color(248, 205, 54));
        btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon("E:\\5.Fork\\On-thi-bang-lai-xe\\LicenseTest\\src\\Images\\User_fill.png")); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setBorderPainted(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        pnlHome.add(btnTaiKhoan);
        btnTaiKhoan.setBounds(170, 400, 420, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLyThuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLyThuyetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLyThuyetActionPerformed

    private void btnThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThiActionPerformed

    private void btnCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCauHoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCauHoiActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCauHoi;
    private javax.swing.JButton btnLyThuyet;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThi;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JPanel pnlHome;
    // End of variables declaration//GEN-END:variables
}
