package testView;

import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import testController.LoginController;

/**
 *
 * @author hai95
 */
public class frLogin extends javax.swing.JFrame {

    /**
     * Creates new form frLogin
     */
    LoginController loginController = new LoginController();
    public frLogin() {
        initComponents();
        setLocationRelativeTo(null);
        JRootPane jrp = this.getRootPane();
        jrp.setDefaultButton(btnLogin);
        txtEmail.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblRegisster = new javax.swing.JLabel();
        pwPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFindPw = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setLayout(null);

        lblRegisster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegisster.setForeground(new java.awt.Color(78, 180, 84));
        lblRegisster.setText("Đăng ký");
        lblRegisster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegissterMouseClicked(evt);
            }
        });
        pnlLogin.add(lblRegisster);
        lblRegisster.setBounds(90, 330, 80, 17);

        pwPass.setBackground(new java.awt.Color(231, 243, 231));
        pwPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 243, 231), 4));
        pnlLogin.add(pwPass);
        pwPass.setBounds(90, 200, 420, 40);

        btnLogin.setBackground(new java.awt.Color(78, 180, 84));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin);
        btnLogin.setBounds(90, 270, 420, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Đăng nhập");
        pnlLogin.add(jLabel1);
        jLabel1.setBounds(220, 30, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email");
        pnlLogin.add(jLabel3);
        jLabel3.setBounds(90, 80, 50, 22);

        lblFindPw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFindPw.setForeground(new java.awt.Color(78, 180, 84));
        lblFindPw.setText("Quên mật khẩu");
        lblFindPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFindPwMouseClicked(evt);
            }
        });
        pnlLogin.add(lblFindPw);
        lblFindPw.setBounds(410, 330, 100, 17);

        txtEmail.setBackground(new java.awt.Color(231, 243, 231));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 243, 231), 4));
        pnlLogin.add(txtEmail);
        txtEmail.setBounds(90, 110, 420, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mật khẩu");
        pnlLogin.add(jLabel2);
        jLabel2.setBounds(90, 170, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegissterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegissterMouseClicked
        // TODO add your handling code here:
        dgRegister register = new dgRegister(Run.home, true);
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegissterMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        mathchesUser();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblFindPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFindPwMouseClicked
        // TODO add your handling code here:
        dgFindPassword findPassword = new dgFindPassword(Run.home, true);
        findPassword.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFindPwMouseClicked

    public void mathchesUser() {
        try {
            String email = txtEmail.getText();
            String pass = pwPass.getText();
            Run.user = loginController.getUserbyEmail(email);
            if (pass.equals(Run.user.getPass())) {
                JOptionPane.showMessageDialog(this, "Login success");
                Run.frHome();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng");
                txtEmail.requestFocus();
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Login failed: " + e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFindPw;
    private javax.swing.JLabel lblRegisster;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pwPass;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
